### ISSUE TITLE
[Doc] Typo in Content Security Policy documentation section

### ISSUE THREAD

**Issue by Loyz07** [Baroshem/nuxt-security#100]
I think there is a typo in the documentation of the [Content Security section](https://nuxt-security.vercel.app/middlewares/headers#content-security-policy) of the doc

### What is Expected?

```js
{
contentSecurityPolicy: {
  value: {
    'base-uri': ["'self'"],
    'font-src': ["'self'", 'https:', 'data:'],
    'form-action': ["'self'"],
    'frame-ancestors': ["'self'"],
    'img-src': ["'self'", 'data:'],
    'object-src': ["'none'"],
    'script-src-attr': ["'none'"],
    'style-src': ["'self'", 'https:', "'unsafe-inline'"],
    'upgrade-insecure-requests': true
  },
  route: '/**'
}
}
```

### What is actually happening?
```js
{
contentSecurityPolicy: {
  value: {
    'base-uri': ["'self'"],
    'font-src': ["'self'", 'https:', 'data:'],
    'form-action': ["'self'"],
    'frame-ancestors': ["'self'"],
    'img-src': ["'self'", 'data:'],
    'object-src': ["'none'"],
    'script-src-attr': ["'none'"],
    'style-src': ["'self'", 'https:', "'unsafe-inline'"],
    'upgrade-insecure-requests': true
  },
   '/**' //TYPO HERE
}
}
```

**Comment by Baroshem** [comment]
Hey,

Thanks for rising this issue, however in this case it is correct. The route property is used to define whether a middleware (route rule) should be enabled for certain route or global.

**Comment by Dez0r** [comment]
@Loyz07 is right. The "route" key is missing in documentation (see his "What is actually happening?" part). There's only the value "/**" without a key.

When copy-pasting the contentSecurityPolicy object from the documentation, the parser throws an error because the object is incorrect

**Comment by Baroshem** [comment]
@Loyz07 @Loyz07 

You guys are right. There is a missing route in the docs. I will fix it for the upcoming docs changes.

Sorry for the trouble and thanks for pointing that out!
