### ISSUE TITLE
use RouteRoules for middlewares

### ISSUE THREAD

**Issue by Baroshem** [Baroshem/nuxt-security#109]
### Is your feature request related to a problem? Please describe.

@harlan-zw

Could you type here your solution so that we could keep track of it? :)

**Comment by Baroshem** [comment]
@harlan-zw 

Do you have any news regarding this feature?

**Comment by harlan-zw** [comment]
Thanks for the ping @Baroshem. I didn't hear back from Pooya but I'm guessing that this implementation is still a good idea.

So currently the current config API does is quite restricted in terms of what rules each route has. To solve this issue we can move the config on to the route rules.

Users should be able to provide route rules with keys for applicable nuxt security config.

For example:

```ts
export default defineNuxtConfig({
  routeRules: {
    '/login': {
      rateLimiter: {
          tokensPerInterval: 30,
          interval: "hour",
        },
      }
    },
    '/api/forms/*': {
      allowedMethodsRestricter: ['POST'],
      requestSizeLimiter: { maxUploadFileRequestInBytes: 9000000 }
    },
  }
})
```

**Comment by Baroshem** [comment]
Hey @harlan-zw 

Thanks for the research and example of the implementation. I agree that this is better option for the future as it will allow to support different rules for different routes (something not achievable right now).

I am just wondering about the interface of the nuxt configuration options to not change it that much so that the current users would be able to easily migrate to the newer version.

**Comment by Baroshem** [comment]
I will work on it for the next release (one after this one) because for the upcoming release I have already some features and bug fixes that should be released first :)

**Comment by Baroshem** [comment]
Just for more context it could work like this:

```ts
export default defineNuxtConfig({
  routeRules: {
    '/api/login': { rateLimit: 5 },
  }
})
```

```ts
const routeRules = getRouteRules(event)
const cachedLimiter = new RateLimiter(routeRules.rateLimit || securityConfig.rateLimiter.value)
```

**Comment by pi0** [comment]
I think we should discuss more in general for Nitro and Nuxt about advising to use `routeRules` by nuxt modules.

There are some important points:
- Additional rules by modules like nuxt-security, can possibly conflict with built-ins unless explicitly prefixed with module name `'/api/login': { nuxtSecurity: { rateLimit: 5 } }`
- Additional rules are platform specific and need to be treeshaken from client bundle and platforms

**Comment by Baroshem** [comment]
If I get your point @pi0 

I shoudn't impelent the routeRules now. is it correct?

I should wait for this discussion to be resolved?

**Comment by pi0** [comment]
As long as we use prefixed namespace `nuxtSecurity: {}` inside route rules, i am fine if you like to include the feature. Only possible downside would be that module needs an update once we introduce route manifest to client-side to enable tree-shaking.

**Comment by Baroshem** [comment]
I see. I will do some research about it and contact you about it once I will have something working :)

Thanks for clarification!

**Comment by Baroshem** [comment]
https://github.com/Baroshem/nuxt-security/releases/tag/v0.13.0
