### ISSUE TITLE
configuring Permissions Policy

### ISSUE THREAD

**Issue by lukeromanowicz** [Baroshem/nuxt-security#117]
### Is your feature request related to a problem? Please describe.
It seems that the module currently does not support Permissions Policy ([docs](https://www.w3.org/TR/permissions-policy-1/),[brief summary](https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/)). It would be nice to add it :)  

### Describe the solution you'd like
Permissions Policy is supported and can be configured accordingly with the features that the app uses. 

### Describe alternatives you've considered
Write some custom code instead, I guess

### Additional context
Nice module btw, pretty time saving

**Comment by Baroshem** [comment]
Hey Łukasz!

Awesome to hear from you. This is a good feature idea indeed. I will take a look at it to add in the next release :)

**Comment by Baroshem** [comment]
Released in https://github.com/Baroshem/nuxt-security/releases/tag/v0.12.0
