### ISSUE TITLE
access-control-allow-origin settings are too lose by default

### ISSUE THREAD

**Issue by lukeromanowicz** [Baroshem/nuxt-security#118]
### Version

nuxt-security: 0.11.0
nuxt: 3.2.3

### Reproduction Link
nuxt-security.vercel.app

### Steps to reproduce
![image](https://user-images.githubusercontent.com/46789227/223073761-a760f24d-b73e-49bf-ad27-23a1c307de18.png)

### What is Expected?
The module gives me full security out of the box.

a) Don't set this header at all leaving the default browser behavior
or
b) Require the user to set this value or at least throw warnings when it's not set

### What is actually happening?
![image](https://user-images.githubusercontent.com/46789227/223073949-773a61f6-a76b-4f1b-b706-646d80522085.png)

**Comment by Baroshem** [comment]
The documentation website just shows how to use the module but does not use it as having these Security middlewares are not necessary for static Markdown website ;)

**Comment by lukeromanowicz** [comment]
I see, makes sense. I made an assumption that it's not only docs but also a demo. In this case please consider this task as a feature request instead of a bug.

**Comment by Baroshem** [comment]
This will be released with upcoming 0.12.0 version

**Comment by Baroshem** [comment]
Released in https://github.com/Baroshem/nuxt-security/releases/tag/v0.12.0
