### ISSUE TITLE
net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep

### ISSUE THREAD

**Issue by stefanisarie** [Baroshem/nuxt-security#132]
### Hey all!

I have the following Stackblitz Nuxt 3 project: https://stackblitz.com/edit/nuxt-starter-7zrwj3?file=nuxt.config.ts

### What I want:
- allow all images from *.akamaized.net to load. 

### What I get:
- the images are blocked and the error is: **`net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep`** 

Am I doing something wrong when specifying which sources are allowed? I've disabled the headers in security settings, but I want to understand what is wrong with my settings?

Thank you!

**Comment by Baroshem** [comment]
Hey @stefanisarie 

I checked your Stackblitz and seems to be working correctly. The image is being served

Could you provide more details? I cannot see the problem you are experiencing :(

**Comment by stefanisarie** [comment]
It still doesn't load for me. Maybe there is something on my network that is blocking the image... I have no clue. Thank you @Baroshem for your reply.

**Comment by Baroshem** [comment]
Let me know if you will still experience the issue. I will do my best to help :)

**Comment by andreasvirkus** [comment]
I'm seeing the same issue after a Slack login for loading the Slack user's avatar (gravatar.com). The avatar loads fine if I disable `nuxt-security`

<img width="593" alt="Screenshot 2023-04-02 at 11 19 14" src="https://user-images.githubusercontent.com/9140811/229341090-e0af5fc2-7160-40d5-9259-e093ad1e6091.png">

**Comment by Baroshem** [comment]
Hey @andreasvirkus 

This is not an issue but an expected behavior. You need to add custom configruation for Content Origin Embedder Policy to work with your Slack case

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy

**Comment by andreasvirkus** [comment]
Hi, thanks that worked great. For anyone finding this in the future, I changed this in nuxt-auth's settings
```js
// nuxt.config.ts
security: {
  headers: {
    crossOriginOpenerPolicy: 'require-corp',
```

And then for those specific/problematic image tags add `crossorigin` attribute
