### ISSUE TITLE
How to allow for images and scripts from external domains?

### ISSUE THREAD

**Issue by JordashTalon** [Baroshem/nuxt-security#138]
I tried installing & setting up the module but it blocks all external images and scripts, how do I allow external images & scripts or allow specific domains?

I tried this to test in nuxt.config.ts:

```
export default defineNuxtConfig({
  modules: ['nuxt-security'],
  security: {
    headers: {
      contentSecurityPolicy: {
        'default-src': ['*'],
      }
    }
  },
})
```

But it didn't seem to have any effect.

**Comment by Baroshem** [comment]
Hey,

Could you please set up a stackblitz link with the issue you are experiencing? I will be glad to show you on the example how to make it work :)

**Comment by JordashTalon** [comment]
@Baroshem Did that link work or did I make it wrong?

**Comment by Baroshem** [comment]
Hey, 

Yes, the link is good. It does not work on Stackblitz but I was able to reproduce it on the local environment. 

Basically, the nuxt-security module sets some security directives that blocks fetching resources from differen host (in your case wikimedia).

To make it work, you have to add this domain to your `nuxt.config.ts` file and more specifically the `security` object for global configuration or in `routeRules` if you use the per-route approach like following:

```ts
export default defineNuxtConfig({
  modules: ['nuxt-security'],
  security: {
    headers: {
      contentSecurityPolicy: {
        'img-src': ['https://upload.wikimedia.org'], // <--- add the domain you want to fetch the image from here
      }
    }
  }
})
```

And also, you will need to add a `crossorigin` attribute to your image tag to instruct the browser that this resource is being fetched from another origin like following:

```html
<template>
  <div>
    <img
      src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Cat_August_2010-4.jpg/272px-Cat_August_2010-4.jpg"
      alt="Cat Image Here"
      crossorigin  // <-- Here
    />
  </div>
</template>
```

You can read more about Content Security Policy (img-src) [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src) and about Cross-Origin Embedder Policy [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy)

I hope that it makes sense.

Let me know if that works for you :)

**Comment by Baroshem** [comment]
To make stackblitz repro work you need to have this configuration enabled:

```ts
  security: {
    headers: {
      crossOriginResourcePolicy: 'cross-origin',
      contentSecurityPolicy: false,
      xFrameOptions: false,
    },
  },
```

Otherwise it will fail. This is some problem on Stackblitz side with following directives.

**Comment by Baroshem** [comment]
Hey @JordashTalon 

Did my answer helped you resolve your issue?

**Comment by Baroshem** [comment]
Hey @JordashTalon

Adding a `crossorigin` attribute to image is a good pattern for having content security policy. If you cannot use it that way (although I recommend using it that way as it is a native browser approach) you can always disable this directive like:

```ts
      contentSecurityPolicy: {
        'img-src': false
      },
```

Or you can enable it globally for all `https` pages like:

```ts
      contentSecurityPolicy: {
        'img-src': ['https:']
      },
```

script src is not working yet as it requires some work on the generated nuxt scripts. For details check out

**Comment by Baroshem** [comment]
@JordashTalon 

I think that right now you can add any script you like because the script src directive is not enabled yet as I need to configure Nuxt to use it.

If it does not work, could you provide more details like error, nuxt config file, etc?

**Comment by JordashTalon** [comment]
Also looks like the image fix stopped working too, I have this config:

```
modules: [
    '@vueuse/nuxt',
    'nuxt-security',
  ],

  security: {
    headers: {
      contentSecurityPolicy: {
        'img-src': false,
      }
    }
  },
```

And looks like external images are still blocked with the same reason.

**Comment by Baroshem** [comment]
That is a very good explanation @alexbidenko1998 , thank you for that!

**Comment by Baroshem** [comment]
@JordashTalon 

Does that answer your question?

**Comment by JordashTalon** [comment]
Yeah good for now
