### ISSUE TITLE
how to respect the protocol on request? (http)

### ISSUE THREAD

**Issue by joseehilton147** [Baroshem/nuxt-security#142]
Im testing your module but got a problem, my local API doenst have SSL, its HTTP and on company this will not be changed for dev, on production has HTTPS.

So how can i handle it here for example:

GET https://dev..companycom.br:8800/api/Authorization/VerifyToken net::ERR_SSL_PROTOCOL_ERROR

it sets HTTPS on request, but my .ENV is HTTP

![image](https://user-images.githubusercontent.com/53986027/231254227-14ae6e6a-315a-4227-8d71-35bd787f838d.png)

![image](https://user-images.githubusercontent.com/53986027/231254741-9d06e2f6-d2ea-4936-a23a-ff2e020eb379.png)

im using axios to fetch

**Comment by Baroshem** [comment]
Hey,

Are you sure that the problem is related to the module? 

Could you please create a reproduction link in stackblitz where your but is reproducable?

**Comment by alexbidenko1998** [comment]
Sourse of your problem may be `'upgrade-insecure-requests': true` in `Content-Security-Policy` ([link](https://nuxt-security.vercel.app/security/headers#content-security-policy)). You can set `false` value - but it is not good.

Alternatively, you can use proxy for your project:

With nuxt you can use nitro routerRules ([link](https://nitro.unjs.io/config/#routerules)). The proxy also means you should use relative path to your api (in a browser or server-side with `$fetch`). If your use different request library, you may need to use ```http://localhost:${process.env.PORT}``` host to api on server side.

```js
nitro: {
  routeRules: {'/api/**': {proxy: 'http://dev.company.com.br:8800/api/**'}},
},
```

Or you can also setup it in a web-server like nginx. It wat means you should send your request through the web-server.

**Comment by joseehilton147** [comment]
yes, i found the problem was really related to Content-Security-Policy, disabling it works, but we decided to not continue using the plugin, anyway ty for your explanation.
