### ISSUE TITLE
Basic auth does not work with nuxt-content

### ISSUE THREAD

**Issue by alexbidenko1998** [Baroshem/nuxt-security#144]
### Version

nuxt-security: 0.13.0
nuxt: 3.4.2
@nuxt/content: 2.6.0

### Description

If I want to use _nuxt-security_ `basicAuth` with nuxt-content, I have been a problem that every page rendered by _nuxt-content_ have **not found error** (not by http code, but on the page). I think the problem is the `basicAuth` middleware is applied on different pages (include `/api/*` routes). And when _nuxt-content_ makes a request to its content ([docs](https://content.nuxtjs.org/api/configuration#api)) it does not pass authorization. Because Authorization header does not pass through internal request. That's what I'm guessing.

Maybe it's worth disabling `basicAuth` for `/api/*` routes?

### Reproduction Link

Repository with this issue - [link](https://github.com/alexbidenko1998/basic-auth-issue).

### Steps to reproduce

Just clone my repository and start it.

### What is Expected?

Default _nuxt-content_ page with `Nuxt Content` h1 (file is `content/index.md`).

### What is actually happening?

Document with not found message on the page:

`Document not found, overwrite this content with #not-found slot in <ContentDoc>.`

**Comment by alexbidenko1998** [comment]
May be something like this can help? https://github.com/Baroshem/nuxt-security/pull/145

**Comment by Baroshem** [comment]
Hey @alexbidenko1998 

Thank you so much for the issue and the PR to fix it. I am currently not able to work on this.

I will be back for maintaining this project in two weeks for now as I will be away.
