### ISSUE TITLE
CSP missing when ssr = false

### ISSUE THREAD

**Issue by jfbloom22** [Baroshem/nuxt-security#149]
I am using Nuxt 3 along with Ionic Capacitor to deploy to Web, iOS and Android.  Web and Android work fine because they do not require a CSP, however iOS does.

I am not 100% sure if this is an issue with nuxt-security or some underlying issue with nuxt.  It is easy enough to replicate and then let me know if it would be better to open an issue on Nuxt's repo.  

### Version

    "nuxt": "^3.2.3",
    "nuxt-security": "^0.12.0"

### Reproduction Link
https://github.com/jfbloom22/nuxt-starter-generate-csp

### Steps to reproduce
- npm install
- npm run generate
- View the /dist/index.html file and observe that the content-security-policy meta tag is not there

### What is Expected?

I expect the content-security-policy meta tag to be there.

### What is actually happening?
It is generating the index.html without the content-security-policy meta tag.

If you switch ssr = true in the nuxt.config.ts.  run `npm run generate` again.  The content-security-policy is in `/dist/index.html`.  

I also tried adding the following in app.vue, but it did not work either with ssr=false:

```
<Meta
   name="content-security-policy"
    content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'"
  />
```

**Comment by Baroshem** [comment]
Hey,

can you check this issue?

https://github.com/Baroshem/nuxt-security/issues/123

**Comment by jfbloom22** [comment]
Yes that is where I got the stackblitz you shared.  I was not able to replicate the issue in stackblitz directly because I do not have access to the /dist folder.  FYI the only thing I changed was adding ssr=false to the nuxt config.

**Comment by Baroshem** [comment]
I see. 

So if I get this right, the problem only appears on the IOS device? On web and Android it works. This is quite strange. Not sure if I can do anything about it from the module side :(

If you use `yarn generate` without setting the ssr=false does it make any difference?

**Comment by jfbloom22** [comment]
The issue effects all 3 platforms, all of them do not have a CSP.  The difference with iOS is that the Capacitor app does not work at all without a CSP.  

Yes, `yarn generate` with ssr=true results in the CSP being added.  

My suspicion is that there is something different about the build process when ssr=false.  I wonder if it is even calling the nuxt-security module?  Any suggestion on how I can verify that?

**Comment by Baroshem** [comment]
Hey @jfbloom22 

Not sure what can be causing the issue then.

You can try to see if for example there are other response headers being set or other security middleqares being applied like rate limiting.

Other than that, I do not know how to help you with that. This is rather an edge case for this module as it is meant to be used in classic web apps.

**Comment by Baroshem** [comment]
@jfbloom22 

Any additional info here?

**Comment by Baroshem** [comment]
Closing the issue as it is an edge case and out of the scope of the regular module behavior (web app).

If there will be more traffic in this topic, the issue can be reopened :)
