### ISSUE TITLE
Problem with CSRF on cloudflare-page

### ISSUE THREAD

**Issue by xTermy** [Baroshem/nuxt-security#150]
### Version

nuxt-security: 0.12.0
nuxt: 3.4.1

### Steps to reproduce

Turn on CSRF on Cloudflare-page building.

### What is Expected?

To build project.

### What is actually happening?

While building (yarn build) I am getting this error:
<html>
<body>

19:53:34.811 | [error] [nitro] RollupError: "randomBytes" is not exported by "node_modules/unenv/runtime/node/crypto/index.mjs", imported by "node_modules/nuxt-csurf/dist/runtime/server/middleware/csrf.mjs".
-- | --
19:53:34.812 |  
19:53:34.812 |  
19:53:34.812 | 1: import { randomUUID, randomBytes, createCipheriv, createDecipheriv } from "crypto";
19:53:34.812 | ^
19:53:34.813 | 2: import { defineEventHandler, getCookie, setCookie, getHeader, createError } from "h3";
19:53:34.813 | 3: import { useRuntimeConfig } from "#imports";
19:53:34.815 | [error] "randomBytes" is not exported by "node_modules/unenv/runtime/node/crypto/index.mjs", imported by "node_modules/nuxt-csurf/dist/runtime/server/middleware/csrf.mjs".
19:53:34.816 | at error (node_modules/rollup/dist/es/shared/node-entry.js:2128:30)
19:53:34.816 | at Module.error (node_modules/rollup/dist/es/shared/node-entry.js:13322:16)
19:53:34.816 | at Module.traceVariable (node_modules/rollup/dist/es/shared/node-entry.js:13707:29)
19:53:34.816 | at ModuleScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:12210:39)
19:53:34.817 | at ReturnValueScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:6953:38)
19:53:34.817 | at ChildScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:6953:38)
19:53:34.817 | at Identifier.bind (node_modules/rollup/dist/es/shared/node-entry.js:8103:40)
19:53:34.817 | at CallExpression.bind (node_modules/rollup/dist/es/shared/node-entry.js:5749:23)
19:53:34.817 | at CallExpression.bind (node_modules/rollup/dist/es/shared/node-entry.js:9630:15)
19:53:34.818 | at VariableDeclarator.bind (node_modules/rollup/dist/es/shared/node-entry.js:5749:23)
19:53:34.921 | error Command failed with exit code 1.
19:53:34.921 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
19:53:34.937 | Failed: build command exited with code: 1
19:53:35.904 | Failed: error occurred while running build command

</body>
</html>

**Comment by Baroshem** [comment]
Hey,

Thanks for reporting this issue. Can you reproduce it locally or is it the Cloudflare deployed app only?

**Comment by xTermy** [comment]
It's only cloudflare deployed app problem.

**Comment by Baroshem** [comment]
I see.

Not sure if I can do anything about it. `csurf` is an external dependency in this module created by @morgbn and the `crypto` is a well known and supported library by Node.js.

**Comment by Baroshem** [comment]
Closing the issue as it is related to third party dependency that I do not have a control.

If anyone will have similiar issue, cors can disabled fron the config
