### ISSUE TITLE
Nuxt config type of per route configuration is not correct

### ISSUE THREAD

**Issue by maxdzin** [Baroshem/nuxt-security#151]
### Version

nuxt-security: v0.13.0
nuxt: v3.x.x

### Reproduction Link

https://stackblitz.com/edit/github-t6dicy

### Steps to reproduce

Try to add per route configuration:

```ts
export default defineNuxtConfig({
  modules: ['nuxt-security'],

  // Per route configuration
  routeRules: {
    'secret': {
      headers: {
        'X-XSS-Protection': '1',
      },
    },
  },
})
```

### What is Expected?
Specified config to be correct.

### What is actually happening?
TS error is thrown due to missed type declaration:
```bash
Object literal may only specify known properties, and 'headers' does not exist in type
```

So, the problem is that the route rules type doesn't include headers and maybe other required options that are supported but not typed:
```ts
interface NuxtSecurityRouteRules {
    requestSizeLimiter?: RequestSizeLimiter | false;
    rateLimiter?: RateLimiter | false;
    xssValidator?: XssValidator | false;
    corsHandler?: CorsOptions | false;
    allowedMethodsRestricter: AllowedHTTPMethods | false;
}
```

**Comment by maxdzin** [comment]
Hi @Baroshem,
While investigating the types issue I also found this thing:
https://github.com/Baroshem/nuxt-security/blob/main/src/module.ts#LL171C43-L171C43

```ts
const setSecurityRouteRules = (nuxt: Nuxt, securityOptions: ModuleOptions) => {
  const nitroRouteRules = nuxt.options.nitro.routeRules;
  delete (securityOptions as any).headers; // Headers were removed from options.
...
```

What is the reason for removing headers while applying per-route config?
I'm not sure, maybe it was supposed before to apply global security headers only rather than to allow to change that from per route config.
But if it is supposed to be allowed by per route config that must be corrected, or `headers` settings from the per route config couldn't be applied. Isn't it?

Thank you!

**Comment by maxdzin** [comment]
Hi @Baroshem 
Thank you, I think I get it.

And, yes, I want to make a PR for fixing this issue.

**Comment by Baroshem** [comment]
Hey @maxdzin 

Awesome! Let me know if you need any help with that :)

**Comment by Baroshem** [comment]
hey @maxdzin 

Can I help you in any way with this? :)

**Comment by maxdzin** [comment]
Hey @Baroshem 
Sorry for taking so long.
I was very busy. I'll try to make a PR soon.

**Comment by maxdzin** [comment]
Hi @Baroshem 
PR is ready

**Comment by Baroshem** [comment]
Closing due to https://github.com/Baroshem/nuxt-security/pull/155#issuecomment-1635351648

**Comment by maxdzin** [comment]
@Baroshem I see. That's OK. It seems my mistake about the place where per-route `headers` config needs to be placed.
Sorry for the possible inconvenience and thank you for clarifying!

**Comment by Baroshem** [comment]
No worries @maxdzin 

Sorry for the long wait time. I hope you will be recomending new features and ideas in the future as I really value your input :)
