### ISSUE TITLE
Does nuxt-security support Nuxt ^3.4.3?

### ISSUE THREAD

**Issue by fresh5447** [Baroshem/nuxt-security#153]
I am just trying to do the most basic of examples but my app blows up the second I add `nuxt-security` to my modules section

    "nuxt": "^3.4.3",
    "nuxt-security": "^0.13.0",

Example:

```
  modules: ['nuxt-security','@nuxtjs/apollo', '@pinia/nuxt', '@vueuse/nuxt'],

  security: {
    headers: {
      crossOriginResourcePolicy: 'cross-origin',
      contentSecurityPolicy: false,
      xFrameOptions: false,
    },
  },


```

The error is 400 bad request

```
at createError (./node_modules/h3/dist/index.mjs:128:15)
at Object.handler (./.nuxt/dev/index.mjs:893:15)
at Object.handler (./node_modules/h3/dist/index.mjs:1247:31)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async toNodeHandle (./node_modules/h3/dist/index.mjs:1322:7)
at async Object.ufetch [as localFetch] (./node_modules/unenv/runtime/fetch/index.mjs:9:17)
at async Object.errorhandler [as onError] (./.nuxt/dev/index.mjs:557:30)
at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1329:9)
```

**Comment by Baroshem** [comment]
Hey,

Thanks for creating this issue. The module works well for sure for Nuxt 3.2.2 as it is the version in the module.

I recently played with it for one of the talks I was doing and then I was using the Nuxt 3.4.3. However it was just a simple application without any dependencies.

Could you tell me if adding nuxt-security without any security configuration works correctly?

**Comment by Baroshem** [comment]
Also, if you could setup a stackblitz repro with your configuration and the error that would have been more than welcome as it will be easier to debug :)

**Comment by fresh5447** [comment]
@Baroshem thanks for the response! The issue arises if I only add the module, no security configuration at all. Simply adding 

  modules: ['nuxt-security','@nuxtjs/apollo', '@pinia/nuxt', '@vueuse/nuxt'],

and of course it is there as I experiment with adding the security config as well.

**Comment by Baroshem** [comment]
Hmm, 

This does nit guide me into where the issue is. The config seems fine.

Basically, the 400 bad request comes (in the module case) from the XSSValidator middleware that validates whether we are not sending JS code as the string to the server. Can you try to disable it from the configuration to see if it makes your app working? Maybe apollo does not work well with xss protection.

**Comment by fresh5447** [comment]
I don't really see how to easily disable the XSSValidator

**Comment by Baroshem** [comment]
@fresh5447 

```ts
export default defineNuxtConfig({
  security: {
    xssValidator: false
  }
})

```

**Comment by Baroshem** [comment]
@fresh5447 

Did you make it work?

**Comment by Baroshem** [comment]
Closing as there is no further contact from the issue author
