### ISSUE TITLE
I have a Cross-Origin-Embedder-Policy blocking issue for a worker.js resource in my public folder

### ISSUE THREAD

**Issue by dataexcess** [Baroshem/nuxt-security#175]
Hello!

I have a nuxt 3 app and when a certain 'boot' button is clicked a synth.worker.js file is loaded from my nuxt public folder. However, the file is not being loaded, in google chrome dev tools it says the file is being blocked by Cross-Origin-Embedder-Policy not being set and should be set to require-corp. 

I tried to use nuxt-security to add the Cross-Origin-Embedder-Policy and all the others, but it is still being blocked. Am I correct in understanding that the settings of nuxt-security only apply to the frontend website itself but not the resources in the /public folder? I am confused.

Said file is located in /public/lib/scserver/scsynth.worker.js 

This is my nuxt.config.ts:
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    devtools: { enabled: true },
    modules: ['@nuxtjs/tailwindcss', '@pinia/nuxt', 'nuxt-security'],
    css: ['@/assets/css/main.css'],
    app: {
        head: {
            title: 'ColliderNFT',
            htmlAttrs: {
                lang: 'en'
            },
            script: [
                {
                    src: 'lib/scserver/scsynth.js',
                    body: true,
                    crossorigin: 'anonymous'
                }
            ]
        }
    },
    routeRules: {
        '/lib': { cors: true }
    },
    security: {
        headers: {
            crossOriginOpenerPolicy: 'same-origin',
            crossOriginResourcePolicy: 'cross-origin',
            crossOriginEmbedderPolicy: 'require-corp',
            contentSecurityPolicy: { 'frame-ancestors': ["'self'", 'https://localhost:3000'] },
            strictTransportSecurity: 'max-age=31536000; includeSubDomains'
        }
    },
    vite: {
        server: {
            headers: {
                'Access-Control-Allow-Origin': '*',
                'Cross-Origin-Embedder-Policy': 'require-corp'
            },
            cors: {
                origin: 'http://localhost:3000'
            }
        }
    }
})
```

Please help me! thank you!

**Comment by Baroshem** [comment]
Hey,

NuxtSecurity adds security response headers to each request that goes through your Nuxt application on the server side. Because of that it does not work fully for static apps and instead we are using the http-equiv of CSP there.

So to answer your question, I dont think that you can use NuxtSecurity to protect a file from your public/static folder.

**Comment by dataexcess** [comment]
But it's not a static app I'm just using npm run dev to build a local server (which is not static I think?). Any idea how I can accomplish what I want? Thank you

**Comment by Baroshem** [comment]
Yes yes, what I meant is that it doesn't work the same on static pages.

Answering:
` Am I correct in understanding that the settings of nuxt-security only apply to the frontend website itself but not the resources in the /public folder` -> NuxtSecurity does not handle files in public folder. It uses browser security response headers to protect content served from the server.

You can enable it globally using the security config in your nuxt.config.ts but I am not sure if it will make it working the way you expect. I don't have exprience with the case you mention so I cannot really help :(

**Comment by dataexcess** [comment]
No worries I fixed it by including the worker.js code inside the file itself and using Blob() instead to create the Worker. i could npot find a solution to the problem but this circumvents it.

**Comment by Baroshem** [comment]
@dataexcess 

Glad that you have found a way to solve it. Closing this issue :)
