### ISSUE TITLE
Permissions-Policy browsing-topics error

### ISSUE THREAD

**Issue by lucianobosco** [Baroshem/nuxt-security#187]
This is my nuxt.config.js content

```
security: {
    headers: {
      contentSecurityPolicy: {
        'img-src': ['https://xxxxxx.nyc3.digitaloceanspaces.com', 'http://localhost:3000'],
      },
      crossOriginEmbedderPolicy: process.env.NUXT_NODE_ENV === 'development' ? 'unsafe-none' : 'require-corp',
    }
},
```

For some reason, all pages in Nuxt 3 throws an error
`Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.`

I tried adding this to headers, but no luck
```
permissionsPolicy: {
        'browsing-topics': ['(self)'],
}
```

Any advice will be appreciated

**Comment by Baroshem** [comment]
Hey,

Damn, this is a really strange thing. I dont even know where to start with this issue. I tried to look for this kind of policy but couldnt find it on the policies list.

Also, your config does not seem to be causing any issues.

You can maybe try to pass the following config

**Comment by lucianobosco** [comment]
> Hey,
> 
> Damn, this is a really strange thing. I dont even know where to start with this issue. I tried to look for this kind of policy but couldnt find it on the policies list.
> 
> Also, your config does not seem to be causing any issues.
> 
> You can maybe try to pass the following config:
> 
> ```ts
> permissionsPolicy: {
>         'browsing-topics': ['*'],
> }
> ```
> 
> If that wont help. I have no other ideas
> 
> Could you create some reproduction Stackblitz link so that I could try it out easily?

I find out that this happens when using an adblocker, so maybe is not related to this package. 
I didn't deploy my app to production yet, but I'm worried that this could happen in live site tho.
The odd thing is that I don't even find the property `browsing-topics` even in mozilla docs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy

**Comment by Baroshem** [comment]
Exactly my case. Could you try to disable the add blocker to see if it makes a difference?

From the module side, I dont think anything can be done as it does not seem to be related to its functionality.

**Comment by Baroshem** [comment]
You can always try to disable/remove the module to see if the problem persists

**Comment by Baroshem** [comment]
@lucianobosco 

Any additional info here?

**Comment by Baroshem** [comment]
Closing due to lack of additional details and probable not related to the module itself.
