### ISSUE TITLE
throwError complains

### ISSUE THREAD

**Issue by csprance** [Baroshem/nuxt-security#188]
### Version

nuxt-security: 0.14.3
nuxt: 3.6.3

### Steps to reproduce
add throwError to a routeRule and notice that it will complain about throwError not being a type

### What is Expected?
to add throwError and not have it add a red squiggly from typescript.

### What is actually happening?
The types are missing from the respective middleware types that you can add throwError to
* RequestSizeLimiter
* RateLimiter
* XssValidator

**Comment by Baroshem** [comment]
Hey, thanks for creating this issue!

It is indeed a bug on the module side. I will review the PR and merge it soon ;)

**Comment by Baroshem** [comment]
Closing the issue as this bugfix was released in 0.14.4 version :)

Thank you!
