### ISSUE TITLE
How to set  csp to Content-Security-Policy-Report-Only instead

### ISSUE THREAD

**Issue by johnson0903** [Baroshem/nuxt-security#193]
Hello, is there an option to set csp to report only? 

Currently I have to read the csp header string in sever plugin and set the string to report only header, then remove the original csp header set by nuxt-security.

**Comment by Baroshem** [comment]
Hey!

By looking at the examples [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only#examples) I would say that you can either add `report-to /csp-violation-report-endpoint/` to the value of CSP if you want to keep this header and also add reporting

or

If you want to only have reporting only, you can always disable the CSP completely:

```ts
// nuxt.config.ts

security: {
  headers: {
    contentSecurityPolicy: false
  }
}
```

And then create a new global header rule for the `Content-Security-Policy-Report-Only` with the usage of `routeRules` in `nuxt.config.ts` file:

```ts
// nuxt.config.ts

  routeRules: {
    '/**': {
      headers: {
        'Content-Security-Policy-Report-Only': '<YOUR_DESIRED_VALUE>'
      },
    },
  },
```

Let me know if that helped :)

**Comment by johnson0903** [comment]
Hi, thank you for providing the solution and 'Report only' is all I want to set on header.

Because in Nuxt 2 [doc](https://v2.nuxt.com/docs/configuration-glossary/configuration-render/#csp), there seem to be an option to set csp report only. Do you think adding this option is a good idea?

**Comment by Baroshem** [comment]
Based on my experience, adding a report only is not beneficial in terms of forcing good security practices by default without configuration needed. It is a good nice to have feature and can be added to the Nuxt 3 app easily in the way I showed above.

If you agree with my explanation, could you close this question issue? I think the answer was given :)

**Comment by johnson0903** [comment]
Ok, thank you for the answer!
