### ISSUE TITLE
Creating an Instance of $fetch in the server/utils leads to error

### ISSUE THREAD

**Issue by Luanovic** [Baroshem/nuxt-security#202]
Hello, 

when I define a $fetch instance via $fetch.create() as a utility function on the server, I get following error after installing nuxt-security: 

ReferenceError: $fetch is not defined

By deleting the utility function, the error vanishes, is there a specific security default that leads to this issue?

**Comment by Baroshem** [comment]
Hey,

I dont think there is anything done on purpose. Rather it is a bug somewhere.

Could you create a stackblitz reproduction?

**Comment by Luanovic** [comment]
https://stackblitz.com/edit/nuxt-starter-rgm24k?file=server%2Fapi%2Fplaceholder.get.ts

**Comment by Baroshem** [comment]
I checked your code and there is some strange error there. When I have added your code it shows the error in the console. 

I have inspected the generated index.mjs file and when the nuxt-security module is enabled there is a different order of the code (your custom fetch is actually registered before the variable `$fetch` becomes globally accessible while when nuxt-security is disabled, it is correctly registered afterwards.

It seems like the nuxt-security nitro plugins are changing the order of your server functions and utils. Not sure if it is an issue on the module or core framework side.

@danielroe do you maybe have some hints what could be an issue here?

**Comment by danielroe** [comment]
Interesting. Issues like this would be caught by auto-importing `$fetch`, as I proposed in https://github.com/unjs/nitro/pull/742.

cc: @pi0

**Comment by pi0** [comment]
Such a workaround requires more top-level logic which causes other issues and blockers for the future development of app entry changes. Would be happy to discuss finding another way to resolve.

Also, this is only a dev issue as we add all chunks in single entry. Production build works fine.

**Comment by Baroshem** [comment]
Thank you guys for the additional details and explanation! 

@Luanovic I think that right now it is more understandable why this issue appear in the dev environment. It is not a desired approach nor a functionality from nuxt-security module.

**Comment by pi0** [comment]
Investigating roto causes why it is breaking with `nuxt-security` module addition. While it is probably something to fix in nitro, using this preset makes module working again:

```ts
export default defineNuxtConfig({
  modules: ["nuxt-security"],
  security: {
    corsHandler: false,
    xssValidator: false,
    rateLimiter: false,
    requestSizeLimiter: false,
    headers: {
      contentSecurityPolicy: false,
    },
  },
});
```

**Comment by pi0** [comment]
So the common issue is `import { getRouteRules } from "#imports"` usage in `nuxt-security` module. As a fix and better usage, you can use `const { routeRules } = event.context._nitro;` however using `security` key in `routeRules` is probably not correct (it means matching `/security` pattern`! Would love to have a chat or pair programming sometime to fix these.

**Comment by Baroshem** [comment]
@Luanovic any feedback from your side?

**Comment by Baroshem** [comment]
Closing the issue as the answer was provided and there is no more contact from the author

**Comment by DamianGlowala** [comment]
This is still a valid issue in latest Nuxt 4, see my minimal reproduction of two similar server exports (one works and the other one does not):

https://github.com/DamianGlowala/nuxt-fetch-not-defined-repro

```
export default defineEventHandler(async () => {
    return await $notWorkingFetch('https://jsonplaceholder.typicode.com/todos/1')
    // return await $workingFetch()('https://jsonplaceholder.typicode.com/todos/1')
})

```
