### ISSUE TITLE
fix: nonce on devtools inline script

### ISSUE THREAD

**Issue by dargmuesli** [Baroshem/nuxt-security#210]
### Version

nuxt-security: 0.14.4
nuxt: 3.7.3

### Reproduction Link

https://stackblitz.com/edit/github-m3mfkv?file=nuxt.config.ts

### Steps to reproduce

Install nuxt-security, have devtools enabled.

### What is Expected?

The devtools inline script receives a `nonce`.

### What is actually happening?

There is no nonce for the devtools inline script, but for the scripts above there is.

![image](https://github.com/Baroshem/nuxt-security/assets/4778485/4644fd10-f539-433a-8075-b694b0eba7ef)

**Comment by dargmuesli** [comment]
Well, adding `'@nuxt/devtools'` to the `modules` array certainly improves things...

**Comment by Baroshem** [comment]
Hey @dargmuesli 

Thanks for reporting this issue. Is it solved already? Everything happened so fast 😃

**Comment by dargmuesli** [comment]
Yep, I got confused about (dev)dependencies and worked to clarify things in https://github.com/nuxt/devtools/pull/425

**Comment by Baroshem** [comment]
Ok, great. Thanks :)
