### ISSUE TITLE
fix: `upgrade-insecure-requests` cannot be turned off for static build

### ISSUE THREAD

**Issue by dargmuesli** [Baroshem/nuxt-security#214]
### Version

nuxt-security: 0.14.4
nuxt: 3.7.3

### Reproduction Link

https://stackblitz.com/edit/github-xdxcbc?file=nuxt.config.ts

### Steps to reproduce

run `nuxt generate`, then `npx serve .output/public` and inspect the content-security-policy header

### What is Expected?

As it's set to `false` in nuxt's configuration there should be no `upgrade-insecure-requests` policy

### What is actually happening?

There is a `upgrade-insecure-requests` policy.

**Comment by Baroshem** [comment]
Hey, 

Thanks for reporting this issue! I have added it in the https://github.com/Baroshem/nuxt-security/pull/212/commits/bf5d18ec02252eeb32bedaabf062ff370b3c4726
