### ISSUE TITLE
request api cannot recieve correct response

### ISSUE THREAD

**Issue by hogking** [Baroshem/nuxt-security#222]
Hi author,  I use Nuxt3 (3.7.3), use prisma and nuxt default server api. 
My web is simple and just has one post api which url is `/api/apply`, method is `post`.
Code:
`server/api/apply/index.post.js`
```
import formidable from "formidable";
import { sendError } from "h3"
import { createApply } from "~/server/db/apply";

export default defineEventHandler(async (event) => {
    console.log("Test api!");
    const form = formidable({})
     ...
    const applyData = {
        ...
    }

    const apply = await createApply(applyData)

    return {
        body: apply
    }
})
```
Everything works well when I do not add nuxt-security to modules.
When I add 'nuxt-security' to modules in nuxt.config.ts, request to `http://localhost:3000/api/apply` cannot receive correct response any more. 
<img width="1632" alt="image" src="https://github.com/Baroshem/nuxt-security/assets/38121483/fe7388de-2c18-4674-b291-b872b06db0ab">
I try to copy nuxt-security whole default config into nuxt.config.ts and change some default configs, still cannot working.
But `console.log("Test api!");` in file `server/api/apply/index.post.js` can still output in terminal.
<img width="1147" alt="image" src="https://github.com/Baroshem/nuxt-security/assets/38121483/19d0700b-ce6b-4b18-95e3-73569c7edfab">

I cannot find any solution. What can I do?
Thank you!

**Comment by Baroshem** [comment]
Hey, 

Do you get any error in your application? Like 400 Bad Request or similar?

**Comment by hogking** [comment]
Hi Baroshem, no error.  
I use formidable to parse event body, I found that it seems that the parsing of body into form in the code cannot run properly, so it cannot return even a response.


The complete code is as follows:
```
import formidable from "formidable";
import { sendError } from "h3"
import { createApply } from "~/server/db/apply";

export default defineEventHandler(async (event) => {
    const form = formidable({})

    const formData = await new Promise((resolve, reject) => {
        console.log("event.node.req:", event.node.req);
        form.parse(event.node.req, (err, fields, files) => {
            if (err) {
                console.log("failed")
                reject(err)
            }
            console.log("success")
            resolve({ fields, files })
        })
    })
    console.log("formData:", formData);
    const { fields } = formData;
    const applyData = {
        phone: fields.phone,
        name: fields.name,
        company: fields.company,
        email: fields.email
    }
    const apply = await createApply(applyData)

    return {
        body: apply
    }
})
```
I add `conlose.log` in file, each request will only output `event.node.req`, but cannot output `failed` or `success`. 
It seems like `formiable` cannot work. I'm a new of nuxt, I don't know if formiable conflicts with nuxt-security, or something went wrong. 

Thanks!

**Comment by hogking** [comment]
I am a new nuxter and I am following a guide video which uses `formidable` package in the tutorial.
I remove`formidable` part, and just use `readBody(event)`, and it works.
This seems to confirm that it is a conflict problem with formidable.

**Comment by Baroshem** [comment]
Yes, I think it is then an upstream issue of this formidable library.

**Comment by hogking** [comment]
Thanks for your answer, Baroshem

**Comment by Baroshem** [comment]
Always there to help. If anything will be not clear or not working as expected, do not hesitate to create an issue or discussion :)
