### ISSUE TITLE
Is it possible to use Basic Auth in SSG mode?

### ISSUE THREAD

**Issue by Zae** [Baroshem/nuxt-security#227]
Is it possible to use Basic Auth in SSG mode?

The documentation is not really clear about this if Basic Auth works when using SSG mode.

Right now I'm getting 401 errors when nuxt is generating the routes.

Is it possible to combine basic auth with SSG?

```
ℹ Prerendering 1 initial routes with crawler                                                                                                 nitro 4:29:10 PM
  ├─ / (3ms)                                                                                                                                                    nitro 4:29:10 PM
  │ └── Error: [401] Access denied
```

**Comment by Baroshem** [comment]
Hey,

The way Basic Auth works in this module is that it sets the appriopriate Response Headers to instruct the browser that this website is using Basic Auth.

So if you are using SSG (static website) that generates static files for each route, then it is not possible to send the response headers.

So in summary, Basic Auth works in SSR not SSG :)

**Comment by Zae** [comment]
That's what I thought, I hoped it might generate some edge specific middlewares / functions to support this.

Thanks for the clarification!
