### ISSUE TITLE
NS_ERROR_FAILURE - Firefox - IFrame Print

### ISSUE THREAD

**Issue by MMontalto** [Baroshem/nuxt-security#228]
Hi, I can't figure out how to solve this problem. I have to implement the printing of a pdf file, I did everything using the iframe, I then create it with the object url deriving from a blob. On Chrome no problem, on Firefox calling the print method I get the following error in console: NS_ERROR_FAILURE
I tried every solution, until I removed nuxt-security and it worked. What type of header or setting can block the print method on firefox?
Thanks for your help

**Comment by Baroshem** [comment]
Hey, I think it can be related to

https://nuxt-security.vercel.app/security/headers#x-frame-options

You can try to disable it like `xFrameOptions: false` or setting it to another value listed here https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

**Comment by MMontalto** [comment]
Thanks for your quick response! Unfortunately it doesn't seem to work even if you disable the xFrameOptions header

**Comment by Baroshem** [comment]
Hmm, thats strange. Could you procide more details like full trace of the error as well as your config?

You can also try to disable all headers 

```ts
security: {
  headers: false
}
```

To see if this is actually about the headers or maybe about one of the middlewares.

**Comment by MMontalto** [comment]
Yes, disabling all the headers worked! Maybe I'll try disabling them one by one until it works

**Comment by MMontalto** [comment]
> Yes, disabling all the headers worked! Maybe I'll try disabling them one by one until it works

Ok founded: crossOriginOpenerPolicy

**Comment by Baroshem** [comment]
This is the second one on my list that I thought could cause this issue 😃

Glad that you managed to find the trouble. 

I will add a note in the docs faq section about your issue so that it will be easier for everyone to fix this issue 🙂
