### ISSUE TITLE
Cannot read properties of null (reading 'getTokensRemaining')

### ISSUE THREAD

**Issue by TrurlMcByte** [Baroshem/nuxt-security#230]
### Version

nuxt-security: v0.14.4
nuxt: v3.7.1

### Reproduction Link
Impossible, only on production heavy load

### Steps to reproduce
do not disable `rateLimiter`

### What is Expected?
clear work

### What is actually happening?
getting errors 
`[nuxt] [request error] [unhandled] [500] Cannot read properties of null (reading 'getTokensRemaining')`
on line `if (cachedLimiter.getTokensRemaining() > 1) {`

Looks like sometimes `cache.get(ip)` disappears after checking 
https://github.com/Baroshem/nuxt-security/blob/0d36fec295e9b8bb2d5749d3330ff88397fe8ac6/src/runtime/server/middleware/rateLimiter.ts#L12
and before getting
https://github.com/Baroshem/nuxt-security/blob/0d36fec295e9b8bb2d5749d3330ff88397fe8ac6/src/runtime/server/middleware/rateLimiter.ts#L16

**Comment by Baroshem** [comment]
Hey,

Thanks for reporting this issue.

In the next two weeks, I will be releasing 1.0.0-rc.1 version of this module where I have completely rewritten the rate limiter to make it better support modern web apps (as it was using quite old approach) and this will resolve this issue as well.

You can check it out here https://github.com/Baroshem/nuxt-security/pull/212/files#diff-e8684b6448fd42764f81853b96094278ba06c63acf1393f3a3508384d6d296c5

This means that I won't be fixing that in the current version (0.14.4). If this is causing problems for your application, I would recommend to disable this built in middleware until the release of the new major version.

It will include some small breaking changes for rate limiter (interval is a number not a string or number) but apart from that I tried to make it as similar as possible to the previous interface.

I will make a note about it in the migration guide.
