### ISSUE TITLE
Deployment Error on Cloudflare Pages: Cannot Find 'nuxt-security' Module

### ISSUE THREAD

**Issue by TheMukhtarAhmed** [Baroshem/nuxt-security#238]
### Version

nuxt-security: 0.13.1
nuxt: 3.4.3

### Issue Description

During deployment on Cloudflare Pages, I encountered an error related to the nuxt-security module. The build process fails with the following error message:

2023-10-09T04:13:42.385704Z [error] Error while requiring module `nuxt-security`: Error: Cannot find module '/opt/buildhome/repo/nuxt-security'

**Additional Information**

- The error occurred during the deployment process on Cloudflare Pages.
- I have confirmed that the `nuxt-security` module is correctly specified in my project's `package.json`. Here are the relevant version details from my `package.json`:
  
  ```json
  {
    "devDependencies": {
      "nuxt-security": "^0.13.1",
      "nuxt": "^3.4.3",
      // ... other dependencies
    }
  }

**Comment by Baroshem** [comment]
Hey, have you tried to move the the module from dev deps to normal dependencies?

**Comment by Baroshem** [comment]
Could you also show me how you are using the module? In either nuxt.config.ts or in the vue components like routeRules?

**Comment by Baroshem** [comment]
Closing as there is no additional details.

Feel free to reopen this issue if the problem persists.
