### ISSUE TITLE
Nonce implementation for style src

### ISSUE THREAD

**Issue by erikknorren** [Baroshem/nuxt-security#239]
Hello,

I recently tried implementing nonce based content-security-policy from the documentation using the config listed below. The script tags in my head all have the nonce attribute and work fine this way. However, my style tags do not. In my app.vue I did the following to try to get it to work as well, however my stylesheets cannot be loaded into the DOM. Is this a bug or am I doing something wrong?

```
onMounted(() => {
  // set nonce to all style tags
  const styleTags = document.querySelectorAll('style')
  for (const styleTag of styleTags) {
    styleTag.setAttribute('nonce', useNonce())
 }
})
```

```
security: {
    nonce: true,
    headers: {
      crossOriginEmbedderPolicy: 'unsafe-none',
      contentSecurityPolicy: {
        'img-src': ['*', 'data:', 'https:'],
        'style-src': [
          "'self'", // fallback value for older browsers, automatically removed if `strict-dynamic` is supported.
          "'nonce-{{nonce}}'",
        ],
        'script-src': [
          "'self'", // fallback value for older browsers, automatically removed if `strict-dynamic` is supported.
          "'nonce-{{nonce}}'",
          "'strict-dynamic'",
        ],
        'script-src-attr': [
          "'self'", // fallback value for older browsers, automatically removed if `strict-dynamic` is supported.
          "'nonce-{{nonce}}'",
          "'strict-dynamic'",
        ],
      },
    },
  },
```

**Comment by Baroshem** [comment]
Hey, thanks for rainsing a question.

I would love to get some feedback from @trijpstra-fourlights who is an expert of nonce ;)

**Comment by trijpstra-fourlights** [comment]
I wouldn't call myself an expert per se ;), but I'm happy to try and help!

The `nonce` attribute cannot be read at runtime by the browser, nor set retroactively which is essentially what you're doing in the `onMounted()` snipplet.

> This is by design (as in, by the browser) because allowing that would defeat the whole purpose of the nonce: "hello browser, this specific resource is absolutely trusted by me, the server. You can check this because the `nonce` attribute is set by me and it matches the CSP header."

To get nonce working, you'll have to provide the nonce attribute when the actual <style> element is created, or use the `useHead` composable which `nuxt-security` supports out of the box.

It makes sense if you think about it: 

__if__ the code in your OP was actually working, it would essentially result in the same as having a CSP with `style-src: unsafe-inline http: https:` as you are blindly trusting anything that has a style tag, i.e. "whatever style element is there, it's trusted".

So either use that as your CSP for style-src, or use `useHead`, or supply the `nonce` attribute when creating the <style> element (either in SFC/JSX or with `document.createElement`).

Hope that helps! If not, can you show how you're injecting/creating the <style> elements that you want to supply with the `nonce` value?

**Comment by erikknorren** [comment]
Thank you very much! I believe I understand what you mean by letting the client generate the nonce after the <style> tag has already been served to the DOM. I use nuxt.config to add either Tailwind or Vuetify to my style, so useHead() isn't really an option I think. My issue ended up being only relevant locally. When importing my stylesheets in app.vue <style> rather than in config it works on production. So I ended up doing this:

```
security: {
    headers: nuxtSecurityHeaders().headers,
  },
```

```
function nuxtSecurityHeaders() {
  if (process.env.NODE_ENV === 'production') {
    return {
      headers: {
        contentSecurityPolicy: {
          'style-src': ["'self'", 'https:', "'nonce-{{nonce}}'"],
          'script-src': ["'self'", "'nonce-{{nonce}}'", "'strict-dynamic'"],
          'script-src-attr': ["'self'", "'nonce-{{nonce}}'", "'strict-dynamic'"],
        },
      },
    }
  }
  return {
    headers: {
      contentSecurityPolicy: {
        'style-src': ["'self'", 'https:', "'unsafe-inline'"],
        'script-src': ["'self'", "'unsafe-inline'"],
        'script-src-attr': ["'self'", "'unsafe-inline'"],
      },
    },
  }
}
```

Thanks a lot!

**Comment by trijpstra-fourlights** [comment]
> Thank you very much! I believe I understand what you mean by letting the client generate the nonce after the <style> tag has already been served to the DOM. I use nuxt.config to add either Tailwind or Vuetify to my style, so useHead() isn't really an option I think. My issue ended up being only relevant locally. When importing my stylesheets in app.vue <style> rather than in config it works on production. So I ended up doing this:
> 
> [...]
> 
> Thanks a lot!

No problem, glad that you got it working :+1: 

It does ring some bells, so I checked my reference project and I indeed also have a similar check implemented:

```
security: {
    nonce: true,
    headers: {
      contentSecurityPolicy: {
        'style-src':
          process.env.NODE_ENV === 'production'
            ? [
                "'self'", // backwards compatibility for older browsers that don't support strict-dynamic
                "'nonce-{{nonce}}'",
                "'strict-dynamic'",
              ]
            : // In dev mode, we allow unsafe-inline for hot reloading
              ["'self'", 'https:', "'unsafe-inline'"],
        'script-src': [
          "'self'", // backwards compatibility for older browsers that don't support strict-dynamic
          "'nonce-{{nonce}}'",
          "'strict-dynamic'",
        ],
        'script-src-attr': ["'self'", "'nonce-{{nonce}}'"],
      },
    },
  },
```

@Baroshem we should probably add this to the `nonce` documentation, what do you think?

**Comment by Baroshem** [comment]
That would be really useful! @trijpstra-fourlights could you create a PR to branch 1.0.0-rc.1? :)

**Comment by erikknorren** [comment]
Thanks, this works out great.  I have one more question, if my component framework (like Vuetify) uses inline-styles i'd have to use unsafe inline right?

**Comment by trijpstra-fourlights** [comment]
> Thanks, this works out great. I have one more question, if my component framework (like Vuetify) uses inline-styles i'd have to use unsafe inline right?

If you cannot control how these inline styles get injected, then indeed your only option to use `unsafe-inline`.

While I haven't tested this, it seems that [vuetify supports supplying a nonce](https://vuetifyjs.com/en/features/theme/#csp-nonce) (although they use a static one in their example, which defeats the purpose).

Also found this [issue](https://github.com/userquin/vuetify-nuxt-module/issues/56#issuecomment-1643461965) which provides some insight on how to approach this:

> We need to add the cspNonce entry in the theme, you can try generating the cspNonce, add a Nuxt Plugin, register vuetify:before-create hook and apply the cspNonce to the theme.

So if you hook into the `vuetify:before-create` hook, you could try to get the current nonce value `const nonce = useNonce()` and apply that to the `cspNonce` parameter on `theme`.

I haven't tested that though, so YMMV. Let us know if you are able to figure it out!
If not, I can probably help you out on getting it to work, but I can't promise on when I'll have time to take a proper stab at it..., so if it's blocking you, your best bet is to go for `unsafe-inline` for now.

**Comment by erikknorren** [comment]
Thanks, you are a saint. I tried to incorporate this but alongside <style> tags, vuetify also inserts inline styles in the html. Such as: 
![image](https://github.com/Baroshem/nuxt-security/assets/86828401/b498bde1-c8a6-4726-a0cd-f2a8f6791d19)
The style tags in the <head> all get proper nonces even without the the theme approach you illustrated. I am quite new to this but I am assuming a nonce cannot be added to an html element that has an inline style attribute rather than a <style> tag element?

**Comment by Baroshem** [comment]
Thanks for extensive research @trijpstra-fourlights and for additional details @erikknorren 💚

After reading your conversion, in my honest opinion, I dont think that this should be added to Nuxt Security. 

In general, it would be useful, but it is a bit of an edge case right now that requires a functionality that as you mentioned will create some overhead for all module users (not only those who are using it) which can be troublesome for performance for example.

This case of Vuetify inline styles shouldnt be a reason to add a feature that will add some dead code for other users. And considering that this issue can be easily mitigated with setting less strict CSP, I would recommend to follow this path now.

But lets keep this idea in mind. Maybe in the future versions, we will be able to implement similar functionality without causing overhead.

Thanks once again for everything!
