### ISSUE TITLE
Nuxt 3.8 dep issues

### ISSUE THREAD

**Issue by glashtin** [Baroshem/nuxt-security#265]
nuxt-security: 1.0.0-rc-2
nuxt: 3.8.0

### Reproduction Link
Change nuxt in package.json to 3.8.0 on your playground on the site and delete the yarn.lock and reinstall

yarn install && yarn run dev

Get the following warnings but the vite warning is causing other issues within nuxt itself and requires with downgrading or removing this module to work correctly.

[1/4] 🔍  Resolving packages...
warning nuxt-security > unplugin-remove > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

warning "nuxt > @nuxt/devtools@1.0.0" has unmet peer dependency "vite@*".
warning "nuxt > @nuxt/devtools > vite-plugin-inspect@0.7.40" has unmet peer dependency "vite@^3.1.0 || ^4.0.0".
warning "nuxt > @nuxt/devtools > vite-plugin-vue-inspector@4.0.0" has unmet peer dependency "vite@^3.0.0-0 || ^4.0.0-0".
warning "nuxt > @nuxt/devtools > @nuxt/devtools-kit@1.0.0" has unmet peer dependency "vite@*".

**Comment by Baroshem** [comment]
Hey, Nuxt Security RC version was released the same day as Nuxt 3.8. 

We have not migrated to 3.8 yet in the module repo. It will be done in the next RC versions but thanks for reporting this! :)

**Comment by Baroshem** [comment]
@glashtin 

In 1.0.0-rc.3 we have migrated to Nuxt 3.8. Could you please check if you still encounter these warnings? :)

**Comment by glashtin** [comment]
Thanks for getting that updated.

On https://nuxt.com/modules/security it states to use the following to update but it fails stating it can not find the RC branch
pnpm add -D nuxt-security@rc

using this works to install the module however.

pnpm add -D nuxt-security@1.0.0-rc.3    

 WARN  1 deprecated subdependencies found: sourcemap-codec@1.4.8
Packages: +9
+++++++++
Progress: resolved 1365, reused 1299, downloaded 1, added 9, done

devDependencies:
+ nuxt-security 1.0.0-rc.3

 WARN  Issues with peer dependencies found
.
└─┬ nuxt-security 1.0.0-rc.3
  └─┬ unplugin-remove 0.1.3
    └─┬ unplugin 0.7.2
      └── ✕ unmet peer vite@"^2.3.0 || ^3.0.0-0": found 4.5.0

Done in 10.5s

Betides the above warnings when installing the module, no other issues detected so far.  The issues I was having when running the compiled code is not longer happening.  👍

**Comment by Baroshem** [comment]
Awesome, thank you for verification @glashtin 💚
