### ISSUE TITLE
implement headers with `routeRules`

### ISSUE THREAD

**Issue by danielroe** [Baroshem/nuxt-security#27]
It feels like you could implement setting various headers with [**routeRules**](https://github.com/unjs/nitro/pull/538) - e.g. a default value imposed via:

```js
export default defineNuxtConfig({
  routeRules: {
    '/**': {
      // default headers
    }
  }
})
```

That way they could also be overridden with other route rules.

Moreover, it would be good to configure `cors` in the same way, and for the same reason. As a heads-up, likely future cors enhancements are anticipated directly within nitro.

**Comment by Baroshem** [comment]
I will implement the route roules the way you recommended but for cors I will leave it for now as it was quite a recent feature :)

Later on I will reconfigure the cors to work similar way

**Comment by maxdzin** [comment]
Hi @Baroshem!

I wondering about the possibility to apply the `headers` rules per route (for example, `contentSecurityPolicy`).
For current nuxt-security v0.13.0 it seems not possible. But maybe you can advise on how to do that?

**Comment by Baroshem** [comment]
Hey @maxdzin 

It is possible.

Take a look at this example file https://github.com/Baroshem/nuxt-security/blob/main/playground/nuxt.config.ts

```ts
export default defineNuxtConfig({
  modules: ['nuxt-security'],

  // Per route configuration
  routeRules: {
    'secret': {
      headers: {
        'X-XSS-Protection': '1' // Here you need to pass 'Content-Security-Policy': 'your values here'
      },
    },
  },
})
```

**Comment by maxdzin** [comment]
Hi @Baroshem!

OK, thank you! So it seems the headers are supported (I didn't yet check that under the hood).

Then at least its declaration needs to be updated, because there's a TS error:
```
Object literal may only specify known properties, and 'headers' does not exist in type
```
The route rules don't include `headers`:
```
interface NuxtSecurityRouteRules {
    requestSizeLimiter?: RequestSizeLimiter | false;
    rateLimiter?: RateLimiter | false;
    xssValidator?: XssValidator | false;
    corsHandler?: CorsOptions | false;
    allowedMethodsRestricter: AllowedHTTPMethods | false;
}
```

**Comment by Baroshem** [comment]
@maxdzin 

Ah I see. You are correct. Could you please create a new issue with this type bug?

If you have some time and would like to contribute, the PR will be more than welcome :)

**Comment by maxdzin** [comment]
@Baroshem Ok, sure. I'll create a PR then.
