### ISSUE TITLE
Clarify `interval`

### ISSUE THREAD

**Issue by dargmuesli** [Baroshem/nuxt-security#270]
https://nuxt-security.vercel.app/documentation/middleware/rate-limiter#interval specifies a default of `300000`. Are those milliseconds? It would be great if there was a better explanation on how to use this property :raised_hands:

**Comment by Baroshem** [comment]
Added in https://github.com/Baroshem/nuxt-security/pull/262/commits/f0f1357f08b4a5a765a3af64931fed0f1af3bf1d :)

Will be released next week with the upcoming 1.0.0-rc.3 version

**Comment by dargmuesli** [comment]
Perfect, thanks! That was quick :fire:
