### ISSUE TITLE
Using nonce for inline script elements with `script-src-attr`

### ISSUE THREAD

**Issue by ymansurozer** [Baroshem/nuxt-security#303]
Hi there!

I am loading the Lemon Squeezy's 3rd party js in my app with `useHead` but for that I need to set my `script-src-attr` to `unsafe-inline`:
```javascript
// In page.vue, **not** inside onMounted hook
useHead({
  script: [
    {
      src: "https://app.lemonsqueezy.com/js/lemon.js",
      defer: true,
      onload: setupLemonSqueezy, // Does the post-load setup
    },
  ],
});

// In nuxt.config.ts
contentSecurityPolicy: {
    "script-src-attr": ["'unsafe-inline'"],
},
```

Of course, I'd prefer not to use `unsafe-inline` there. So I tried this to use a nonce approach:
```javascript
// In page.vue, **not** inside onMounted hook
useHead({
  script: [
    {
      src: "https://app.lemonsqueezy.com/js/lemon.js",
      defer: true,
      onload: setupLemonSqueezy,
      nonce: useNonce(), // I understand this is a utility provided by Nuxt Security?
    },
  ],
});

// In nuxt.config.ts
contentSecurityPolicy: {
    "script-src-attr": ["'nonce-{{nonce}}'"],
},
```

But this nonce approach does not work because I get this error:
```
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src-attr 'nonce-019l8soupC90awZL7QaK/A=='". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
```

I tested `useNonce` inside the page to see what value it returns, but it appears to return `undefined`, so I am not sure how to use that, too.

Do you have any ideas what I am doing wrong here? Simply, I'd like to use a nonce and avoid `unsafe-inline` while using the `onload` callback of `useHead`.

**Comment by ymansurozer** [comment]
Thank you very much @vejja, this was immensely helpful! I now understand the issue and solved my case with `unsafe-hashes`.

**Comment by Baroshem** [comment]
Thanks @vejja for the amazing help once again. You are a rockstar! 🚀
