### ISSUE TITLE
Nuxt 3.8.1 breaks Subresource Integrity

### ISSUE THREAD

**Issue by vejja** [Baroshem/nuxt-security#305]
No SRI attributes in SSG mode

### Version

nuxt-security:  1.0.0-rc.4
nuxt:  ^3.8.1

### Reproduction Link

https://stackblitz.com/edit/nuxt-starter-3x8r6t?file=README.md

### Steps to reproduce

Open Stackblitz repro with DevTools, inspect Response

### What is Expected?

`<head>` elements should contain `integrity` attributes

### What is actually happening?

`<head>` elements do not contain `integrity` attributes

### Issue description

The issue only appears in SSG mode. SSR mode is not affected.
The Stackblitz repro installs in SSG mode to illustrate the issue.
<img width="701" alt="Capture d’écran 2023-11-28 à 11 06 18" src="https://github.com/Baroshem/nuxt-security/assets/7295259/d0441dbc-c20f-412b-b959-0a2761c2c99a">

You can modify the `nuxt` version to 3.8.0 and the issue will disappear
<img width="699" alt="Capture d’écran 2023-11-28 à 11 06 05" src="https://github.com/Baroshem/nuxt-security/assets/7295259/50eb83e4-2c3a-4ab6-9a0d-d79916fab5a2">

### Origin of issue

Nuxt 3.8.1 modified the behavior of the `nitro:build:public-assets` hook.
- Before 3.8.1, this hook was called before pre-rendering pages
- After 3.8.1, this hook is now called after pre-rendering pages

Responsible commit was https://github.com/nuxt/nuxt/commit/a4b333bca2a729b2629d45212b12eb8e046f47be#diff-85b4fe47ac4284e88552626029d5147793563b4dcdab205cd8dc6afb190222aaR462

### Resolution

PR #304 will fix

**Comment by Baroshem** [comment]
@vejja once again, thank you si much for both finding and fixing an issue! 💚
