### ISSUE TITLE
Unrecognized Content-Security-Policy directive 'undefined'.

### ISSUE THREAD

**Issue by marcaureln** [Baroshem/nuxt-security#307]
### Version

nuxt-security: 1.0.0-rc.4
nuxt: 3.7.4

### Steps to reproduce

nuxt.config.ts

```ts
export default defineNuxtConfig({
  ...
  modules: ['nuxt-security'],
  security: {
    headers: {
      crossOriginOpenerPolicy: false,
      crossOriginEmbedderPolicy: false,
      contentSecurityPolicy: false,
    },
  },
...
});
```

### What is Expected?

This warning shouldn't be printed in the browser console because `contentSecurityPolicy` is set to false.

### What is actually happening?

Got: `Unrecognized Content-Security-Policy directive 'undefined'.` in browser console.

**Comment by vejja** [comment]
@marcaureln You're right
PR #304 will fix
For now you can set `contentSecurityPolicy: ''` to avoid the console warning

**Comment by marcaureln** [comment]
Thanks @vejja !

The empty string didn't fix it. But tried `' '` (single space) and the warning vanish. Can't wait to use the upcoming release.

**Comment by Baroshem** [comment]
@vejja Thanks guys for finding and solving it!

Aiming to release it with 1.0.0-rc.5 soon :)
