### ISSUE TITLE
Zaraz not working

### ISSUE THREAD

**Issue by krisnegi123** [Baroshem/nuxt-security#308]
I am using Cloudflare Zaraz for Analytics, but it doesn't work when I have enabled Nuxt Security module. It gives me this error:

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'`

**Comment by Baroshem** [comment]
Hey,

It is related to the strict CSP of Nuxt Security.

Check out following link about allowing inline elements

https://nuxt-security.vercel.app/documentation/advanced/strict-csp#allowing-inline-elements-for-nuxt

**Comment by vejja** [comment]
Related : #309 

Can you try disabling the auto-injection of Zaraz and instead load it with :
```ts
useHead({
  scripts: [
    { src: "/cdn-cgi/zaraz/i.js", crossorigin: true, referrerpolicy:"origin" }
  ]
}, { mode: 'client' })
```

As instructed in https://developers.cloudflare.com/zaraz/advanced/load-zaraz-manually/

**Comment by Baroshem** [comment]
@krisnegi123 any feedback from your side?

**Comment by Baroshem** [comment]
Closing the issue due to lack of details
