### ISSUE TITLE
Allow falling back to global options when per-route option is not provided

### ISSUE THREAD

**Issue by toto6038** [Baroshem/nuxt-security#310]
### Is your feature request related to a problem? Please describe.

Nuxt Security requires providing a `security` object in `defineRouteRules`. I suggest that it should be allowed to omit it, and fallback to global options such as the one defined in `nuxt.config.ts` if per-route option is not provided.

<img width="1127" alt="image" src="https://github.com/Baroshem/nuxt-security/assets/50100922/bb5fcabf-629e-42c1-a115-f75c70081877">

### Additional context

Versions
```
> pnpm dlx nuxi info
------------------------------
- Operating System: Darwin
- Node Version:     v18.18.2
- Nuxt Version:     3.8.1
- CLI Version:      3.10.0
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.10.2
- Builder:          -
- User Config:      css, devtools, modules, imports, pinia, postcss, gtm, security, runtimeConfig, sitemap, experimental
- Runtime Modules:  @nuxtjs/tailwindcss@6.9.4, @pinia/nuxt@0.5.1, @nuxt/image@1.0.0-rc.1, @vueuse/nuxt@10.6.1, nuxt-lodash@2.5.3, nuxt-security@0.14.4, @zadigetvoltaire/nuxt-gtm@0.0.13, @nuxt/content@2.9.0, @vueuse/nuxt@10.6.1, nuxt-simple-sitemap@4.1.6
- Build Modules:    -
------------------------------
```

**Comment by Baroshem** [comment]
Hey @toto6038 

Thanks for reporting this suggestion. Could you please try if the same issue appears on the RC version? :)

**Comment by toto6038** [comment]
@Baroshem Yes, I can verify that the problem still appears on v1.0.0-rc.4. TypeScript raises the same error.

**Comment by vejja** [comment]
@Baroshem I think it will disappear in rc5 because security in NitroRouteConfig is now typed as optional:

```ts
declare module 'nitropack' {
  interface NitroRouteConfig {
    security?: Partial<NuxtSecurityRouteRules>;
  }
}
```
Not 100% sure though because I did not check it separately with `experimental.inlineRouteRules`, but would sound logical
