### ISSUE TITLE
declare module '@nuxt/schema' breaks RuntimeConfig's type determination.

### ISSUE THREAD

**Issue by kiki-kanri** [Baroshem/nuxt-security#319]
### Version

nuxt-security: v1.0.0-rc.5
nuxt: v3.8.2

### Reproduction Link

v1.0.0-rc.4 https://stackblitz.com/edit/github-czgrdm-zhuae5

v1.0.0-rc.5 https://stackblitz.com/edit/github-czgrdm-ca4shv

### Steps to reproduce

Open the rc.4 and rc.5 repositories and check the runtimeConfig.testServerString type in server/api/index.ts.

### What is Expected?

In the rc.5 version of the repository, the type of `runtimeConfig.testServerString` is string.

### What is actually happening?

The type of `runtimeConfig.testServerString` is either any or unknown.

After testing, I found that changing "declare module '@nuxt/schema'" back to "declare module 'nuxt/schema'" can fix the problem.

It is assumed that the use of @nuxt/schema overwrites the definitions in the `.nuxt/types/schema.d.ts` file and causes the types in the runtimeConfig object to be missing from the other package settings.

**Comment by vejja** [comment]
@kiki-kanri 
Thanks for not only reporting, but also providing the fix 🚀

PR #320 fixes
