### ISSUE TITLE
FrameAncestors is ignored in SSG while being added to Meta tag

### ISSUE THREAD

**Issue by Baroshem** [Baroshem/nuxt-security#329]
### Version

nuxt-security: ex: v1.0.0
nuxt: v3.8.2 

### Steps to reproduce

1. Create app with Nuxt Security
2. Build as SSG
3. Open DevTools Console
4. Observe `The Content Security Policy directive 'frame-ancestors' is ignored when delivered via a <meta> element.` error in the console

### What is Expected?

Frame-ancestors in SSG is ignored so we could programatically remove it from the meta tag. 

### What is actually happening?

A bug in the console appears

**Comment by danielvodnansky** [comment]
It happens for me now, is there any fix?

**Comment by Baroshem** [comment]
@danielvodnansky what version of the module do you use?
