### ISSUE TITLE
Favicon.ico missing

### ISSUE THREAD

**Issue by Baroshem** [Baroshem/nuxt-security#332]
![image](https://github.com/Baroshem/nuxt-security/assets/37120330/aacffb03-eb20-40f3-91a0-c10f7fefd49b)

**Comment by pothuraju-dev** [comment]
@Baroshem is this issue still exists? I see a PR got merged recently

**Comment by Baroshem** [comment]
Yes, PR was merged but I have not yet released the 1.1.0 version where I have plnned to release it.

Will be published this or next week :)
