### ISSUE TITLE
Export headers for SSG apps to import in nginx.conf

### ISSUE THREAD

**Issue by mtdvlpr** [Baroshem/nuxt-security#336]
### Is your feature request related to a problem? Please describe.
When using this modules for a SSG app, the headers are correctly used in development, but there's no way to extract the generated headers to import them in the server configuration for the deployment server.

### Describe the solution you'd like
I would like the headers to be exported into a `headers.conf` file for example. So that I can use the [nginx include](https://nginx.org/en/docs/ngx_core_module.html#include) function to import them.

### Describe alternatives you've considered
The alternative is that I set all headers manually and don't use this module at all.

**Comment by Baroshem** [comment]
Hey buddy,

Thanks for reporting this issue idea. I have very little experience with Nginx to be honest so I cannot really say much about it.

I completely understand the reasoning why you may want it but I am not sure if we can deliver something from the module side that would be useful for the majority of module users.

Maybe you have some idea already? I understand the case of exporting headers as headers.conf but how do you see it in more details? Would it be a script that would transform headers from `defaultConfig.ts` file? Or maybe a log in the console after build with the headers that are set for the app?

I would appreciate your feedback :)

**Comment by vejja** [comment]
I am not sure whether this falls within the scope of this module.
To me it sounds more like
- Either a new module idea for Nginx users
- Or a feature request for an `nginx_static` preset in `unjs/nitro` 

On the other hand, we do already compute headers for the exact same use case that OP is talking about. But currently they can only be used with the Vercel and Netlify Nitro presets. There is no `nginx` preset in Nitro.

One way we could introduce some flexibility would be to provide a custom hook with the value of the headers. It would then be the responsibility of the user to generate the correct `headers.conf` file or whatever other output ?

**Comment by Baroshem** [comment]
Hey @vejja 

Great to have you back! 🚀

Thanks for providing this idea to @mtdvlpr . Maybe it will allow to get the desired output already.

In terms of implementing this as a part of the module. I agree with you that it can be outside of the scope of the security module to have this functionality.

If the solution you provided will work, I would recommend to add a note in FAQ about how this can be achieved for easier discovery.

Let me know guys what you think about it.

**Comment by Baroshem** [comment]
@mtdvlpr have you tried the solution provided by @vejja ?

**Comment by mtdvlpr** [comment]
Hi @Baroshem I haven't tested it yet, but I have tested the Netlify preset and that's exactly what I want! Only get the headers in a different format for nginx. I will create a custom preset and maybe create a PR so it gets added to the nitro presets as an nginx preset. So I consider this issues resolved.

**Comment by Baroshem** [comment]
Awesome, glad that you managed to make it work! 🚀

I will close the issue now.

If you will have any ideas in the future about what we could do to make the module better, do not hesitate to let us know through issues here.

Happy coding! ⚡️

**Comment by mtdvlpr** [comment]
Hi @Baroshem, quick question. Since I'm now extracting the headers, including CSP, and importing them in my nginx config, I don't need the CSP meta tag that's generated. Is there a way to disable the meta tag but keep the CSP configuration?

**Comment by Baroshem** [comment]
Hey @mtdvlpr 

AFAIK, we dont have this option right now so if you select this rendering mode in your build config nuxt security will automatically detect it and set up either the headers (SSR) or meta (SSG).
