### ISSUE TITLE
Parser error in combination with @nuxtjs/html-validator module

### ISSUE THREAD

**Issue by OmnomnomTee** [Baroshem/nuxt-security#337]
### Version

nuxt-security: v1.0.0
nuxt: v3.9.0
@nuxtjs/html-validator: v1.6.0

### Reproduction Link

Default nuxt project with nuxt-security and @nuxtjs/html-validator modules, available on stackblitz.

https://stackblitz.com/edit/nuxt-security-html-validator-bug?file=nuxt.config.ts

### Steps to reproduce

1. Create default nuxt project
2. Add @nuxtjs/html-validator module
3. Add nuxt-security module
4. Run the project in dev mode or build it for prod -> error in console

### What is Expected?

Project builds without errors, when enabling the nuxt-security module.

### What is actually happening?

Getting a html-validator error, when the module is activated.

```
HTML validation errors found for /

inline
  11:201  error  failed to tokenize "=\"\"><div c...", expected attribute, ">" or "/>"  parser-error
```

**Comment by vejja** [comment]
It looks like Cheerio is modifying Vue `data-v-...` tags to `data-v-...=""`, and @nuxtjs/html-validator complains about this.
This is absolutely valid HTML though, I do not understand why html-validator has a parser issue with this.
Is there a way you can setup html-validator to not complain about empty string attributes ?

**Comment by OmnomnomTee** [comment]
Thanks for the fast reply! 

@Baroshem I am currently using both modules for the rewrite of my portfolio website, but it is not open source yet, which is why I created the minimal project on Stackblitz. I will open source the repo sometime this week, as I am also having another issue regarding the Vercel build pipeline and the nuxt-security module.

@vejja Thanks for the hint regarding Cheerio. I will take a look at the @nuxtjs/html-validator configuration options. Apparently it uses html-validate under the hood. The configuration options can be found here: 
[https://html-validate.org/rules/index.html](https://html-validate.org/rules/index.html)

I will report back when i know more.

**Comment by Baroshem** [comment]
Hey @OmnomnomTee 

Thanks for the reply, let us know once you will have more details.


Also, thanks @vejja for hints :)

**Comment by OmnomnomTee** [comment]
Just a brief update, disabling the html-validate rules did not address the issue. I am currently taking a deeper look, but have not as much time as I would want. Will keep you posted.

**Comment by Baroshem** [comment]
Ok no worries. Let us know if we can help somehow and with the further progress on this :)

**Comment by Baroshem** [comment]
@OmnomnomTee 

Any progress? :)

**Comment by Baroshem** [comment]
Closing the issue. If it will be needed, please do not hesitate to reopen it and provide additional details so that we can help :)
