### ISSUE TITLE
Find a way to override 'X-Powered-By' header 

### ISSUE THREAD

**Issue by Baroshem** [Baroshem/nuxt-security#35]

**Comment by Baroshem** [comment]
@danielroe

Maybe you will be able to help here :)

**Comment by danielroe** [comment]
This is set here: https://github.com/nuxt/framework/blob/cfaa46201ac284ea4bd2d8f8ba35d48d82156276/packages/nuxt/src/core/runtime/nitro/renderer.ts#L248-L256

It can be overridden in the `render:response` nitro hook: https://github.com/unjs/nitropack/blob/859a9843a0258a02fe1fb6785dad5907d5c4d0c3/src/runtime/renderer.ts#L33.

**Comment by Baroshem** [comment]
And would you also point me to resources on how I can create a nitro plugin from inside of a nuxt module? I know how to access nuxt hooks but not nitro plugin. And nitro documentation does not help either :(

**Comment by danielroe** [comment]
Sure. Here's a module that does it: https://github.com/nuxt-modules/html-validator/blob/main/src/module.ts#L29-L42

**Comment by Baroshem** [comment]
Thanks Daniel! It is now pretty clear to me how it is supposed to work. I will work on this in the upcoming days :)
