### ISSUE TITLE
Object literal may only specify known properties, and 'throwError' does not exist in type 'CorsOptions'.

### ISSUE THREAD

**Issue by imcm7** [Baroshem/nuxt-security#352]
After update to latest packages

> Object literal may only specify known properties, and 'throwError' does not exist in type 'CorsOptions'.

```
corsHandler: {
      origin: 'http://localhost:3000',
      methods: ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE'],
      preflight: {
        statusCode: 204
      },
      throwError: true,
    },
```

In example is the same, with throwError https://nuxt-security.vercel.app/documentation/getting-started/configuration

**Comment by Baroshem** [comment]
Hey,

Thanks for rising the issue. The problem is in the documentation as CorsHandler does not accept a throwError property.

Would you be interested in contributing with a documentation fiz to remove the property from Cors?

I can provide all help needed :)
