### ISSUE TITLE
CSRF - Add a plugin that provide a $fetch wrapper with csrf automatically added

### ISSUE THREAD

**Issue by ankita2104** [Baroshem/nuxt-security#360]
### Is your feature request related to a problem? Please describe.
https://github.com/Morgbn/nuxt-csurf/issues/4

### Describe the solution you'd like
A convenient wrapper around $fetch so that it automatically adds the CSRF token in headers.
https://github.com/Morgbn/nuxt-csurf?tab=readme-ov-file#csrffetch

**Comment by Baroshem** [comment]
Hey,

if you set `security.csrf: true` it should add an auto import for all CSRF related functionalities (including `useCsrfFetch`)

https://nuxt-security.vercel.app/documentation/middleware/csrf

**Comment by Baroshem** [comment]
Any news @ankita2104 ?

**Comment by ankita2104** [comment]
yes, I can use useCsrfFetch composable for $fetch also. So closing this issue now

**Comment by Baroshem** [comment]
Thanks for letting me know :) Happy coding!
