### ISSUE TITLE
XSS validator per route

### ISSUE THREAD

**Issue by mozhgan-k** [Baroshem/nuxt-security#362]
Hi, I have an issue with disabling the XSS validator in a specific route. According to the documentation, if I want to disable it for a specific route, I should use the following configuration:

```
// Per Route
routeRules: {
  '/my-secret-route': {
    security: {
      xssValidator: {
        // options
      }
    }
  }
}
```

However, when I use it in my nuxt.config, it doesn't seem to work. I want to enable it globally and disable it for just one of my routes.

Here is my nuxt.config:

```
security: {
  headers: {
    xssValidator: {
      throwError: true
    },
  },
  routeRules: {
    '/myRoute': {
      security: {
        xssValidator: false
      }
    }
  },
}

```

**Comment by Baroshem** [comment]
Hey @mozhgan-k 

In your config you have security.headers.rateLimiter which is not correct.

Headers object only applies to browser response headers such as Content Security Policy.

Rate limiter is nested inside security only:

```ts

security: {
    xssValidator: {
      throwError: true
  },
  routeRules: {
    '/myRoute': {
      security: {
        xssValidator: false
      }
    }
  },
}
```

**Comment by mozhgan-k** [comment]
It worked. thank you
