### ISSUE TITLE
Wrong Example for setting runtime hooks

### ISSUE THREAD

**Issue by marcel-wtfoxtrot** [Baroshem/nuxt-security#365]
### Version

nuxt-security: 1.1.0
nuxt: 3.9.3

I'm afraid there is a small error within the recommended runtime hook configuration.

I've tried 
```
export default defineNitroPlugin((nitroApp) => {
    nitroApp.hooks.hook('nuxt-security:ready', () => {
        nitroApp.hooks.callHook('nuxt-security:headers', '/**' ,{
            contentSecurityPolicy: {
                "script-src": ["'self'", "'unsafe-inline'"],
            },
            xFrameOptions: false
        })
    })
})
```

but this results in an error. The Hook arguments seem to be incorrect.

```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)

```

By proving all args as an object it seems to work just fine

```
nitroApp.hooks.hook('nuxt-security:ready', () => {
    nitroApp.hooks.callHook('nuxt-security:headers', {
      route: '/**',
      headers: {
        contentSecurityPolicy: {
            "script-src": ["'self'", "'unsafe-inline'"],
        },
        xFrameOptions: false
      },
    })
  })
  ```

**Comment by Baroshem** [comment]
Hey @marcel-wtfoxtrot 
Thanks for reporting this issue.

Would you be interested in fixing it? I can provide all help needed :)

**Comment by Baroshem** [comment]
Also @huang-julien coukd you take a look at it?

**Comment by huang-julien** [comment]
oops 🤦‍♂️  i forgot to update the docs when i refactored the pr following harlan's suggestion. Want me to fix it ?

**Comment by Baroshem** [comment]
Please do! 

I can then merge it and publish the new documentation fix for that :)

**Comment by Baroshem** [comment]
Thank you @huang-julien so much! 💚
