### ISSUE TITLE
Are runtimeHooks only intended for the headers?

### ISSUE THREAD

**Issue by genu** [Baroshem/nuxt-security#371]
Its not clear from the documentation, but it seems like runtime hooks only really work with overrwriting headers but not `previous configuration` as it indicates?

Can I, for example, override the `enabled` flag under `basicAuth`?

**Comment by Baroshem** [comment]
Hey there!

Good question. From the implementation made by Julien I think it is only aimed to work with headers.

https://github.com/Baroshem/nuxt-security/pull/298

So I dont think you could use it for basicAuth as it works differently (it is not a header per se but rather a middleware)

**Comment by Baroshem** [comment]
Hey @genu 

Did I answer your question? :)

**Comment by genu** [comment]
Yes, thx
