### ISSUE TITLE
Can't make another rateLimiter driver work (Vercel KV)

### ISSUE THREAD

**Issue by MickL** [Baroshem/nuxt-security#372]
I cant make another driver (vercel kv) work and the Docs dont explain how to do it. Am I supposed to put just the name string or the driver itself?

I tried:

```ts
import vercelKVDriver from 'unstorage/drivers/vercel-kv';

//...
security: {
    rateLimiter: {
      tokensPerInterval: 3,
      interval: 300000,
      driver: vercelKVDriver({
        // Tried with and without:
        // url: process.env.KV_REST_API_URL,
        // token: process.env.KV_REST_API_TOKEN,}),
    },
}
```

And it actually works: If I refresh the page 4 times I am banned. But if I check the Vercel KV (Redis) it shows zero entries: `KEYS *`.

**Comment by Baroshem** [comment]
Hey, 

In order to implement it correctly, you would need to define a driver like following:

https://github.com/Baroshem/nuxt-security/blob/main/src/defaultConfig.ts line 52

**Comment by MickL** [comment]
Thanks I will give it a try! The thing is that it doesnt say if `driver` needs to be just a string name or a driver object while linking to Unstorage which always created a driver object:

```
const storage = createStorage({
  driver: vercelKVDriver({
});
```

Further, if it only requires a name, how do I know what name is the one I am looking for example is it cloudflare-kv or cloud-flare-kv or cloudFlareKv or cloudFlareKV?

**Comment by Baroshem** [comment]
1. tokensPerInterval is necessary for the rate limiting to work (same as interval). If you dont want to change the defaut values, you can always set them as the same as in the default config -> https://nuxt-security.vercel.app/documentation/middleware/rate-limiter#tokensperinterval

**Comment by MickL** [comment]
Yes it works fine and I close this issue. Thanks for the quick responses! The docs need to be updated tho :)

**Comment by Baroshem** [comment]
Ok, so let me reopen this issue so that we can link the documentation fix to it :)

**Comment by Baroshem** [comment]
Managed to do it faster 😃

Added in https://github.com/Baroshem/nuxt-security/commit/4327422f973e7d340ed20aba51a5123838a1e286

Closing
