### ISSUE TITLE
Mention about expected behavior of security config declared globally vs via `defineRouteRules`

### ISSUE THREAD

**Issue by DamianGlowala** [Baroshem/nuxt-security#385]
### Is your feature request related to a problem? Please describe.

Users (including myself) might be uncertain how security config defined via `defineRouteRules` behaves compared to globally declared one without looking into the source code or experimenting.

### Describe the solution you'd like

Mention in the docs describing the above behaviour (are these configs merged, replaced, etc.).

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by Baroshem** [comment]
Hey @DamianGlowala 

Thanks for this issue!

I have added it to 1.3.0 milestone planning :)
