### ISSUE TITLE
gtm-support nonce missing

### ISSUE THREAD

**Issue by joerees** [Baroshem/nuxt-security#389]
I am using this module in conjunction with  "@gtm-support/vue-gtm": "^2.1.0" with nonce enabled.

As the GTM script is loaded dynamically via the module, it is not adding the nonce to the the GTM scipt node.

The GTM script initialisation has an option to pass the nonce. So the question is how can i get this nonce value from the nuxt-security module ?

**Comment by Baroshem** [comment]
Hey,

What about using https://nuxt-security.vercel.app/documentation/headers/csp#nonces-for-ssr?

**Comment by Baroshem** [comment]
You should also be able to use https://github.com/Baroshem/nuxt-security/blob/main/src/runtime/composables/nonce.ts

**Comment by Baroshem** [comment]
Hey @joerees 

Do you need any additional help?

**Comment by vejja** [comment]
Hi @joeres,
I would have thought that if you are using CSP with `strict-dynamic` (which is the default setup of Nuxt-Security), you should not have to insert the nonce yourself.
But it all depends on how @gtm-support/vue-gtm is loading the GTM script. Could you share a repro or some additional info on the error ?

**Comment by Baroshem** [comment]
Closing as there is no further activity.

If needed, do not hesitate to reopen the issue :)

**Comment by dariasamo** [comment]
I have similar issue. I am using vue-gtm plugin for adding gtm support to my project. I add it as a nuxt plugin and I try to pass the nonce value from useNonce composable.
```
export default defineNuxtPlugin((nuxtApp) => {
    const config = useRuntimeConfig();
   const nonceValue = useNonce();

    nuxtApp.vueApp.use(
        createGtm({
            id: 'GTM-xxx'
            defer: false,
            compatibility: false,
            enabled: true,
            loadScript: true, 
            trackOnNextTick: false, 
            nonce: nonceValue // it is an empty string
        })
    );
});
```
As far as I can see, useNonce will only return nonce value when ssr context is available, so I can't get it on the client. Any idea how I can tackle it in this particular case? Thank you.

**Comment by vejja** [comment]
Hi @dariasamo 

As far as I understand, you are trying to get the nonce value on the client. This is not possible.
As you mentioned rightly, the nonce value is only accessible in the server. Clients cannot insert nonces by themselves, as this would defeat the point of CSP nonces.

Can you share a bit more about your setup (SSR, SSG, Nuxt version) and how vue-gtm works for you ?

**Comment by dariasamo** [comment]
Hi @vejja thanks for explanation, it makes sense.
It's Nuxt 3.10.3, universal mode, nuxt-security 1.2.0. I use vue-gtm to simplify sending tracking to gtm. I considered adding gtm script manually with useHead, so adding nonce is handled automatically but then I lose the route navigation tracking which vue-gtm handles out of the box. There is an option to use a vue-gtm [wrapper for Nuxt](https://nuxt.com/modules/nuxt-gtm) with it's configuration in nuxt config but I would still have to pass the nonce value somehow:
`
export default defineNuxtConfig({
  ...
  gtm {
    ...
   nonce: ... // ?
  }
})
`

**Comment by vejja** [comment]
I don't know how vue-gtm inserts the gem script, but can you try using that wrapper without setting the nonce option ?
Also let me know, when you hit your index page, is the `<script>` tag for GTM already included in the server response ? You will need to inspect the `<head>` section of the raw HTML response in the Network tab of the inspector (not the Elements tab)

**Comment by dariasamo** [comment]
I tried using it without setting the nonce but then there is no nonce added on the script tag, so there are CSP errors. Regarding your second question, I just checked and it's not there yet.

**Comment by vejja** [comment]
Ok so this means that vue-gtm is not inserting the tag from the server-side
In that case there should be no CSP errors if you are using strict-dynamic mode.
Can you share a screenshot of the CSP errors in the console ?

**Comment by vejja** [comment]
@dariasamo 
Let me know if you need any help
The GTM doc section you mention does not use `strict-dynamic`, which is our default and which disable domain whitelisting.
Normally you should be fine with `strict-dynamic`, if it's not the case I'm glad to help
