### ISSUE TITLE
Adding package leads to build errors Code Unable to Build - Nuxt Build Error: [vite:build-import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files 

### ISSUE THREAD

**Issue by nosizejosh** [Baroshem/nuxt-security#390]
Adding this package to my code leads to errors and prevents build.
more on this error on this nuxt issue here [https://github.com/nuxt/nuxt/issues/26011](url)

### Version

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  npm@10.4.0
- Builder:          -
- User Config:      runtimeConfig, devtools, modules, ui, css, app, supabase
- Runtime Modules:  @nuxtjs/supabase@1.1.6, @vueuse/nuxt@10.9.0, @pinia/nuxt@0.5.1, @nuxt/ui@2.14.1, @pinia-plugin-persistedstate/nuxt@1.2.0, nuxt-icon@0.6.8, nuxt-security@1.2.1
- Build Modules:    -
------------------------------

**Comment by vejja** [comment]
Hi @nosizejosh 

According to your original bug report, your file `D:/proj/components/details/Index.vue:205:64` indeed contains invalid javascript in the `unMounted` hook
It could potentially be related to `removeLoggers`, would you be ok to share your original code in the unMounted hook? It looks like vite transformed your original code.

**Comment by nosizejosh** [comment]
hello @vejja 

```
onUnmounted(() => {
    removeCardServiceSubscription(cardServicesSubscription)
    console.log("🚀 ~ onUnmounted ~ removeCardServiceSubscription(cardServicesSubscription):", removeCardServiceSubscription(cardServicesSubscription))
});
```

**Comment by vejja** [comment]
No problems @nosizejosh !
FYI `removeLoggers` is a small additional utility to the core of Nuxt-Security that removes `console.log` outputs in production. We are using the unplugin-remove package to do so but apparently there is a bug there and I think it is related to emojis.
By setting `removeLoggers: false` in the config, we are not purging the browser console from your logs, but the rest of the Nuxt-Security core is still active.

**Comment by vejja** [comment]
@Baroshem FYI upstream was fixed today

**Comment by Baroshem** [comment]
Awesome, thanks @vejja !

I will add a bump of the package on our side and release it with the upcoming 1.3.0 release :)
