### ISSUE TITLE
how to allow access to api routes from a dynamic list of known origins

### ISSUE THREAD

**Issue by nosizejosh** [Baroshem/nuxt-security#391]
Hello, I am new to nuxt-security.

I am writing a set of APIs that I want to block access to all other origins except from a list of known origins. My application is multitenant so only tenants should be able to access this set of APIs. 
This list will be updated periodically. 

How do I go about implementing this as first layer of security?

Thank you.

**Comment by Baroshem** [comment]
Hey Buddy,

Thanks for asking this question. From your use case, I would go for Cross Origin Resource Sharing (CORS).

https://nuxt-security.vercel.app/documentation/middleware/cors-handler

**Comment by nosizejosh** [comment]
Thanks for your response.

I implemented this in a middleware rather.

Thanks!
