### ISSUE TITLE
verify if limiters could be implemented as Nitro plugins instead of server middlewares

### ISSUE THREAD

**Issue by Baroshem** [Baroshem/nuxt-security#4]
<img width="828" alt="image" src="https://user-images.githubusercontent.com/37120330/194724262-253ce0c1-a8d9-41d3-9f3c-939f2e4326b3.png">

**Comment by itpropro** [comment]
+1 for providing the functionality as pure [Nitro plugin](https://nitro.unjs.io/guide/advanced/plugins).

**Comment by Baroshem** [comment]
Thanks @itpropro 

I am not sure when I could take this issue and tryto work on it but I am also not sure how. The docs about nitro are not very great so I would probably have to figure it out by myself ;)

**Comment by itpropro** [comment]
> Thanks @itpropro
> 
> I am not sure when I could take this issue and tryto work on it but I am also not sure how. The docs about nitro are not very great so I would probably have to figure it out by myself ;)

Maybe @danielroe can help with that. I think it would also benefit nitro's docs having a real-world plugin example.

**Comment by danielroe** [comment]
what's the question? The main difference is that nitro plugins are run per nitro instance whereas middleware are per request. this means they can have state that is 'outside' an event context.

**Comment by Baroshem** [comment]
I know already how to create nitro plugins but I have recently replaced server middlewares with routeRoules that should do the trick.

I am closing for now.

**Comment by itpropro** [comment]
I just saw that this issue was closed, is the Nitro plugin available somewhere @Baroshem? I am mainly using Nitro without Nuxt and would like to use it there.

**Comment by Baroshem** [comment]
Hey,

The nitro plugin in this module is used to hide X-Powered-By header. I tried to use it for developing loic that is cirrently done as middlewares but I dont think it is possible to have the same result
