### ISSUE TITLE
Wrong paths on Windows

### ISSUE THREAD

**Issue by mikeschepers4** [Baroshem/nuxt-security#42]
Hello, i was trying to import the module inside my project but after importing the module i always seem to be getting the following error.
![image](https://user-images.githubusercontent.com/86236312/199477621-7445bfbd-83f0-4f70-b24d-c7eb0151776f.png)

This error happens in my own project but also when i setup a completely empty nuxt project with nothing in it.

```
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: ["nuxt-security"],
});
```

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.12"
  },
  "dependencies": {
    "nuxt-security": "^0.5.0"
  }
}
```

**Comment by Baroshem** [comment]
Hey @mikeschepers4 

Are you using Static Site Generation or SSR?

**Comment by Baroshem** [comment]
This is really strange, I have just tested it out on a same project and it works (the only difference is that I am using yarn I believe)

<img width="949" alt="image" src="https://user-images.githubusercontent.com/37120330/199492305-d1fd48a0-8f3a-4ceb-8fec-fb76f6e5ab36.png">

Package.json:

```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.12"
  },
  "dependencies": {
    "nuxt-security": "^0.5.0"
  }
}
```

Nuxt.config.ts

```ts
export default defineNuxtConfig({
    modules: ['nuxt-security']
})
```

**Comment by mikeschepers4** [comment]
It seems to happen both in ssr and static site generation. I tried to make a stackblitz but there it doesnt happen. 

I think it might have something to do with the operating system since my error complained about a bad character sequence. (the error is in my screenshot above). Could windows have something to do with it?

**Comment by mikeschepers4** [comment]
![image](https://user-images.githubusercontent.com/86236312/199493290-004dbd11-39a2-4162-8a2e-91f8e3a346ba.png)
these are the lines that are causing the issue on my system

**Comment by mikeschepers4** [comment]
adding .replace(/\\/g, '/') after every resolve call seems to fix the build. i will let you know if everything works as i expected

**Comment by Baroshem** [comment]
I see, quite strange. I will ask around in the nuxt community. From what you say, this bug can be caused by nuxt itself.

**Comment by mikeschepers4** [comment]
I think the problem lies in [this file](https://github.com/Baroshem/nuxt-security/blob/main/src/module.ts) here the resolve methods dont seem to normalize the paths correctly for windows at least.

The output seems to be like this: `C:\rovict\nuxt-app\node_modules\nuxt-security\dist\runtime\server\middleware\requestSizeLimiter `

Whilst you need this output on windows: C:/rovict/nuxt-app/node_modules/nuxt-security/dist/runtime/server/middleware/requestSizeLimiter

**Comment by danielroe** [comment]
Yes, exactly. It can be resolved in this project by using `pathe` instead of `path`. We can probably also normalise in `addServerHandler` etc. in kit.

**Comment by Baroshem** [comment]
@danielroe so should I update the module itself to use pathe instead of path or will this be something included in the next version of kit?

**Comment by danielroe** [comment]
You should use `pathe` anyway.

**Comment by Baroshem** [comment]
Ok, so I will replace this for the next version. Thanks for the help!

**Comment by Baroshem** [comment]
@mikeschepers4 I will release the new version in the upcoming days with this fix and few other smaller functionalities.

**Comment by mikeschepers4** [comment]
Amazing! I'll keep an eye on it. Thanks for the quick response!

**Comment by Baroshem** [comment]
Hey @mikeschepers4 

I have released a new version with the fix for that. Could you please check if it works right now? :)

**Comment by mikeschepers4** [comment]
Just updated the module to check. there still seems to be an issue. I'll look into this a bit deeper. (tested with a newly created nuxt app)
![image](https://user-images.githubusercontent.com/86236312/199978424-25ce37c0-9c82-41ee-b18e-2735dd9dd19e.png)

**Comment by Baroshem** [comment]
@mikeschepers4 

I see, maybe then changing the path to pathe is not enough. Let me know please after you do some more testing. Unfortunately I do not have a Windows device so I cannot really test it out (almost like blind coding). I can also release a quick patch version to make it work

**Comment by Baroshem** [comment]
Or for each middleware replace `handler: resolve(runtimeDir, 'server/middleware/rateLimiter')` with `handler: normalize(resolve(runtimeDir, 'server/middleware/rateLimiter'))`

**Comment by Baroshem** [comment]
Any news @mikeschepers4 ? 🙂

**Comment by mikeschepers4** [comment]
Sorry ran out of time to test it last week. will test today :)

**Comment by mikeschepers4** [comment]
Ive not been able to find a solution. I think it may have something to do with the way nitro is referencing the given paths. ill look further once i have some time again

**Comment by Baroshem** [comment]
@danielroe Could you take a look at that? Maybe this is an issue in the nitro?

**Comment by Baroshem** [comment]
hey @mikeschepers4 

Have you managed to test it out more?

**Comment by mikeschepers4** [comment]
Sorry no. I think a potential fix would be to make use of relative paths instead of absolute paths. But i dont know how easy that would be to integrate in this solution. 

Or Nitro needs to make a fix to handle absolute paths correctly on windows machines. 

I sadly dont have a lot of time at the moment to work that out myself

**Comment by Baroshem** [comment]
@danielroe @pi0

I managed to test it out on an old Windows laptop and the issue is appearing when I want to push Nitro plugin from module:

https://github.com/Baroshem/nuxt-security/blob/1c93c65bb53eb9607df1c8ab970f79f74d68c13e/src/module.ts#L34

Other URL;s are working correctly. Is it caused by this? https://github.com/nuxt/framework/pull/8626/files

I have updated the package to work with 3.0.0-rc.13 version but the issue is still there

**Comment by danielroe** [comment]
In dev mode this likely needs to be a file URL not a path. Fancy testing that? If so, we can likely fix in Nuxt itself.

**Comment by Baroshem** [comment]
Related to https://github.com/nuxt/framework/issues/8461

**Comment by Baroshem** [comment]
I tested it by sending even a simple path to the plugins array, it still shouts that it is not correct.

**Comment by Baroshem** [comment]
I believe this is an issue on the nitro side as other handlers are working correctly, only the one that is being pushed to nitro plugins array is failing.

For all users facing the problem. When you set `hidePoweredBy` to `false` in your nuxt.config.ts your project will work fine and you can use it as a workaround now until a proper fix will be published. It will disable this plugin for now but will make your app working.

**Comment by mikeschepers4** [comment]
Can confirm that your workaround is working. thanks :)

**Comment by Baroshem** [comment]
Guys, 

Daniel is already working on fixing this issue on the nitro side. I will make sure to update nuxt to a newer version once it is released. For now, make sure to use this workaround -> https://github.com/Baroshem/nuxt-security/issues/42#issuecomment-1311727911

**Comment by Baroshem** [comment]
Hey folks, 

I have tested solution from @pi0 and it seems to be working now. Please test it out in your environment and let me know if there are any issues. Sorry that it tooked so long and hope that you will be still using the module :)
