### ISSUE TITLE
Support SWR

### ISSUE THREAD

**Issue by MarijnFK** [Baroshem/nuxt-security#428]
When using a SWR option in routeRUles, the nonce-header does not match the one served from the server:

### Version
nuxt-security: 1.3.2
nuxt: 3.11.x

### Steps to reproduce
enable swr on all routes:
```
routeRules: {
    "*": {
      swr: process.env.NODE_ENV === "development" ? false : parseInt(process.env.SWR_TTL ? process.env.SWR_TTL.toString() : "60"),
    },
  },
```

### What is Expected?
The header should use the generated nonce value
![image](https://github.com/Baroshem/nuxt-security/assets/47977238/9c8e2bd7-eee6-43a9-afe0-b2b6f68c3651)
![image](https://github.com/Baroshem/nuxt-security/assets/47977238/6224d610-bd2d-4376-b83d-d23ea37ebdd5)

### What is actually happening?
The header uses the new nonce, but the html served is using the nonce that was used when generating the page

**Comment by Baroshem** [comment]
Thanks for the investigation @vejja 

I would probably go for the second option but maybe @danielroe would have a better idea? :)

**Comment by vejja** [comment]
Let me investigate better because I actually think we can support natively without moving to hash mode

**Comment by vejja** [comment]
@MarijnFK would you be able to share a minimal Stackblitz repro of a basic use case ?
I'd like to check that we can indeed support SWR on a relevant setup

**Comment by MarijnFK** [comment]
@vejja I've made a very simple stackblitz, it's not really a use-case but it shows the problem.
[stackblitz](https://stackblitz.com/~/github.com/MarijnFK/nuxt-security-swr-example)

The top date shows the ssr-date. It should update every 10 seconds. 
The bottom date should be hydrated, but doesn't  because the script is blocked from executing

**Comment by vejja** [comment]
> @vejja have you maybe checked if this new solution of yours works with the stackblitz repro providede by @MarijnFK ?

Yes, I included an equivalent example in the playground under the `/swr` page there, it is testable with `yarn dev` and then going to `localhost:3000/swr`

**Comment by MarijnFK** [comment]
@vejja Good to hear, looking forward to the update! Thanks for the (quick!) responses
