### ISSUE TITLE
Install module with the nuxi module add command trigger a warning

### ISSUE THREAD

**Issue by damevin** [Baroshem/nuxt-security#436]
### Version

nuxt-security: 1.3.0
nuxt: 3.10.0

### Steps to reproduce

Install the nuxt module with the command `npx nuxi@latest module add security`

This warning message should appears 
```
[WARN]t seems that security is not a Nuxt module.
✔ Do you want to continue installing `security` anyway?
```

### What is Expected?

This message should not appears, i think it's introduced by [this MR ](https://github.com/Baroshem/nuxt-security/pull/410/files)

**Comment by Baroshem** [comment]
This is an interesting issue because I have just tried the command in my hello world nuxt app and this is the result:

![image](https://github.com/Baroshem/nuxt-security/assets/37120330/98a3d725-14c8-4bc0-8820-62ba5904b679)

@vejja could you try it?

**Comment by Baroshem** [comment]
@danielroe do you have any idea why @damevin can experience such result? Is it due to the version of some dependencies maybe?

**Comment by maxdzin** [comment]
@Baroshem same, works with `security`, as stated above, and with v1.4.2 paths are resolved correctly, so no more errors.

**Comment by damevin** [comment]
Ok that's very weird 😅
When I retry it works now... i'm sorry

**Comment by Baroshem** [comment]
@damevin 

No worries buddy! Thanks for retesting!

Happy Coding :)
