### ISSUE TITLE
RollupError: Could not resolve `../../../utils`

### ISSUE THREAD

**Issue by schaubes** [Baroshem/nuxt-security#438]
After todays update to v1.4.0 using pnpm I get following error:
```
ERROR  RollupError: Could not resolve "../../../utils" from "node_modules/.pnpm/nuxt-security@1.4.0_rollup@4.16.4/node_modules/nuxt-security/dist/runtime/nitro/plugins/00-routeRules.mjs"
```

### Version

nuxt-security: v1.4.0
nuxt: v3.11.2

### Reproduction Link

Can post if necessary

### Steps to reproduce

Initializing a new nuxt app with pnpm and adding nuxt-security

```bash
npx nuxi@latest init test-app
cd test-app/

# add nuxt-security
npx nuxi module add security

# run dev server with pnpm
pnpm run dev
```

### What is Expected?

`pnpm run dev` should start normally

### What is actually happening?

```
ERROR  RollupError: Could not resolve "../../../utils" from "node_modules/.pnpm/nuxt-security@1.4.0_rollup@4.16.4/node_modules/nuxt-security/dist/runtime/nitro/plugins/00-routeRules.mjs"
```

**Comment by MarijnFK** [comment]
Jup, same here

**Comment by Baroshem** [comment]
Hey, thanks for reporting this issue. We are on it!

**Comment by Baroshem** [comment]
This is really strange. At first I thought that the issue is related to wrong dist generation (I copied the dist to the node modules of the project) and project started working.

But it can be something else, still investigating.

**Comment by vejja** [comment]
> It should work now with 1.4.2. @MarijnFK @schaubes could you verify?
> 
> @vejja I needed to add a copy of `defuReplaceArray` to the utils of the runtime. The import works locally but fails when released in a published dist package.

Ah yes makes sense now

**Comment by garyellow** [comment]
> It should work now with 1.4.2. @MarijnFK @schaubes could you verify?
> 
> @vejja I needed to add a copy of `defuReplaceArray` to the utils of the runtime. The import works locally but fails when released in a published dist package.

It works with v1.4.2
thx~~

**Comment by MarijnFK** [comment]
Quickly fixed, thanks!
