### ISSUE TITLE
routeRules import paths error in v1.4.0

### ISSUE THREAD

**Issue by maxdzin** [Baroshem/nuxt-security#439]
### Version

nuxt-security: v1.4.0
nuxt: v3.11.2

### Reproduction Link
https://stackblitz.com/edit/github-ymby1y

### Steps to reproduce
Just see the console output

### What is Expected?
Nuxt app to be launched without errors.

### What is actually happening?
```
[nitro 10:34:45 AM]  ERROR  RollupError: Could not resolve "../../../utils" from "node_modules/nuxt-security/dist/runtime/nitro/plugins/00-routeRules.mjs"
```

It seems need to be `../../utils` instead. And the paths in files inside `dist/runtime/nitro/plugins/...` need to be checked as well.

**Comment by maxdzin** [comment]
Oops! It seems already reported in another issue #438 while I prepared this one 😄

**Comment by Baroshem** [comment]
Can you guys try 1.4.2? I tried it and it seems to be working :)

**Comment by maxdzin** [comment]
@Baroshem it works. I removed the module from deps and installed it via command:
`npx nuxi@latest module add security`
now it is added as dependency (previously it was dev dependency). I already asked that in the discussion: is there a reason to move that to deps instead of dev deps?

**Comment by Baroshem** [comment]
Closing the issue then. @maxdzin lets continue this discussion in the discussion created by you :)
