### ISSUE TITLE
Nitro provides a built-in storage useStorage (memory and redis)

### ISSUE THREAD

**Issue by Maxp777** [Baroshem/nuxt-security#44]
### Version

nuxt-security: last
nuxt: 3 last

### Steps to reproduce
Example: Simple (in memory) operations

```
await useStorage().setItem('test:foo', { hello: 'world' })
await useStorage().getItem('test:foo')
```

Example: redis operations
```
await useStorage().setItem('redis:foo', { hello: 'world' })
await useStorage().getItem('redis:foo')

export default defineNitroConfig({
  // Production
  storage: {
    'db': {
      driver: 'redis',
      /* redis connector options */
    }
  }
  ```
### What is Expected?
But you use package like memory-cache

**Comment by Baroshem** [comment]
Hey,

Yes, I tried using unstorage for storing banned ip's in the storage but it was not working because rate-limiter needs to be stored fully (as an object with properties, methods, and reactive values) not as a stringified value which ustorage does by default.

Thanks for the recommendation though! In other cases it would for sure be useful to replace memory-cache with unstorage :)

**Comment by Maxp777** [comment]
need to open an issue to solve that :)

**Comment by Baroshem** [comment]
Ok, if you have an idea on how to make it work, I can reopen the issue. Please create a pull request and I will test this out :)

**Comment by Maxp777** [comment]
issue to open for nitro, why they limit us to not use objects?

**Comment by Baroshem** [comment]
In general, storing stringified values in the storage is ok (for example to store result of a https request in cache) but in this particular case, I need to store something else and here memory-cache works fine

**Comment by Maxp777** [comment]
@Baroshem https://github.com/unjs/nitro/issues/639#issuecomment-1305366760

**Comment by Baroshem** [comment]
@Maxp777 

The answer in the referenced issue does not help in any case in my opinion. What is even the motivation here? Even when you will manage to create a custom method that will force unstorage to store raw values, in the best scenario you will replicate the current functionality with unstorage (and in my opinion you will force the tool to work in a different way that it is meant to work).

I don't think that this feature is actually needed but let me know what do you think about it.

**Comment by Maxp777** [comment]
it's strange to have functionality like useStorage and can't have possibility to used :)
and to use additional package
