### ISSUE TITLE
SRI breaks the application on mobile devices

### ISSUE THREAD

**Issue by GalacticHypernova** [Baroshem/nuxt-security#453]
### Version

nuxt-security: ^2.0.0-beta.5
nuxt: ^3.10.3

### Reproduction Link

N/A. I have spoken with @Baroshem on the matter and we have decided to start with a mere explanation about the bug and without a reproduction, since the nuxt-security playground is also broken on mobile devices (which could be for the same, or a similar, reason) and the bug happened within a closed source project.

### Steps to reproduce

Don't disable SRI, go to the app on mobile, and you should be met with an error page that it failed to load the dynamically imported module.

### What is Expected?
SRI should work fine and not break the app on mobile devices.

### What is actually happening?
SRI is breaking the app on mobile devices (desktop works fine)

**Comment by vejja** [comment]
Hi @GalacticHypernova 
Can you give more details about the circumstances under which SRI fails on mobile, a log of the errors reported by the browser, or a reproducible example ?
The documentation page of Nuxt Security is deployed with SRI and works fine on mobile devices. I’d like to understand why it works on that deployment but not on another one ?

**Comment by GalacticHypernova** [comment]
Hey @vejja , the details about the issue are pretty vague as mobile devices don't have dev tools enabled by default and I am trying to connect to my phone from my PC to debug it remotely, but from what I gathered so far I saw a couple things:
1. SRI causes the app to fail with an error message stating "failed to fetch dynamically imported module website.com/_nuxt/index.[file hash].js", but the file does load when going to the file URL directly.
2. Regarding the errors, I don't have them currently due to what I said, but I did notice that when checking the site performance using lighthouse (https://pagespeed.web.dev), at least according to the snapshots it provided, it didn't seem to fail. When trying to enter it on a "real" mobile device it does however. This was tested on 2 separate mobile devices and across mobile browsers.
3. The stackblitz playground is also broken on mobile devices so I could not create a reproduction yet.

**Comment by vejja** [comment]
Which browser are you using for the stackblitz playground ?

**Comment by GalacticHypernova** [comment]
I'm using chrome, the actual app where it failed was tested on chrome and edge

**Comment by vejja** [comment]
ok Chrome is fine
can you set crossOriginEmbedderPolicy to credentialless so that stackblitz will get correct isolation ?

**Comment by vejja** [comment]
Do you have `enabled : false` also ?

**Comment by GalacticHypernova** [comment]
Yes, I tried disabling it, but I think because there's no `ctrl + s` combination in the changes can't get applied and therefore it doesn't do anything

**Comment by vejja** [comment]
If you have `enabled : false`, the module is completely disabled.
What's your testing setup ? Is the playground running on mobile here ?

**Comment by GalacticHypernova** [comment]
> If you have `enabled : false`, the module is completely disabled.

That's if the changes actually apply, which they don't seem to, considering it's still stating that. The playground is ran on mobile here

**Comment by vejja** [comment]
I'm not sure stackblitz can run on mobile.
https://developer.stackblitz.com/platform/webcontainers/browser-support

Can you run stackblitz on desktop and connect your mobile via local network. Then launch the dev tools on your desktop to observe the mobile logs

**Comment by GalacticHypernova** [comment]
That's what I'm gonna have to try

**Comment by vejja** [comment]
Ok
Also you said SRI failed on mobile _in production_
How do you deploy? Which hosting provider are you using?

**Comment by GalacticHypernova** [comment]
> How do you deploy? Which hosting provider are you using

My apologies, this was a slightly misleading statement. I haven't tested in dev mode yet as I'm deploying on a self hosted server (not server less, full ssr)

**Comment by GalacticHypernova** [comment]
@vejja I have made some more testing (of the actual app, not stackblitz), and found a few more things:
Let's say my mobile device is phone A, and the other mobile device is phone B. When I attached phone A to my desktop and launched the debugger with the devtools instance (made sure to rebuild the app), it briefly fixed SRI for both phone A and B. Now, phone A works perfectly fine with SRI, but phone B is once again broken.

**Comment by vejja** [comment]
Which server are you using?
And is your app a PWA?

**Comment by GalacticHypernova** [comment]
Using a self hosted server by ultahost (I believe at least), the app is not a PWA. As stated above, I couldn't check mobile logs because as soon as I attached the local debugger to my device it somehow fixed it for every mobile device

**Comment by vejja** [comment]
Sounds more like a cache issue than an SRI issue
Shall we close or do you want to keep open?

**Comment by GalacticHypernova** [comment]
Yea we can close it, sorry about that! I'm not entirely sure it was a cache issue considering it was across different devices and different browsers which guaranteed at least one of the time it would be fresh data,  and it definitely doesn't explain the local debugger fixing the global issue, but at least it works now. Thanks a lot for the help!

**Comment by Baroshem** [comment]
Hey guys,

Thanks for extensive research. I completely missed this issue yesterday due to other tasks.

Great that together you have found a solution! 🎉
