### ISSUE TITLE
Version 2.0.0-rc.1 fails to start

### ISSUE THREAD

**Issue by AaronDewes** [Baroshem/nuxt-security#462]
### Version

nuxt-security: 2.0.0-rc.1
nuxt: 3.11.2

### Reproduction Link

Let me know if you need one, but this seems to affect all new installations.

### Steps to reproduce

Use nuxt-security.

### What is Expected?

It works

### What is actually happening?

```

 ERROR  RollupError: Could not resolve "../../../defaultConfig" from "node_modules/nuxt-security/dist/runtime/server/middleware/requestSizeLimiter.mjs"                                                             nitro 19:09:26

```

This looks like a mistake in the build.

![grafik](https://github.com/Baroshem/nuxt-security/assets/67546953/11ea2ff2-0f84-487e-9c7f-1cc8ed335274)

The extension is missing here, and the defaultConfig.mjs file does not seem to exist as part of the bundle.

**Comment by vejja** [comment]
@AaronDewes you're right, patching now

**Comment by AaronDewes** [comment]
Thank you!
