### ISSUE TITLE
CSRF per route

### ISSUE THREAD

**Issue by moshetanzer** [Baroshem/nuxt-security#469]
Hi,

Love your library.

Can you have CSRF enabled globally and per route disable (for e.g., logout endpoints etc..)

This doesnt work
```

 '/api/auth/logout': {
      security: {
        csrf: false
      }
    }

```

**Comment by vejja** [comment]
Hi @moshetanzer 
Under the hood we use the [Nuxt-Csurf module](https://github.com/morgbn/nuxt-csurf) by @Morgbn, which has route-level support, so I think it should be available under its native `csurf` option key.
Could you try to do 
```
'/api/auth/logout': {
  csurf: false
}
```
And let me know if it works ?

**Comment by moshetanzer** [comment]
yip, suspected that 😄. Should I add a pr to docs or to codebase?

**Comment by vejja** [comment]
Yes please, that would be wonderful !
Thanks

**Comment by Baroshem** [comment]
Thanks guys!
