### ISSUE TITLE
Nuxt security with Socket.io and xssValidator make POST requests hanging

### ISSUE THREAD

**Issue by noook** [Baroshem/nuxt-security#472]
### Version

nuxt-security: `2.0.0-beta.5`
nuxt: `3.11.2`

### Reproduction Link

https://github.com/noook/nuxt-security-socket-io-repro

### Steps to reproduce

1. Run the project linked
2. Open devtools, network tab
3. Click the "Emit event button"
4. Observe POST requests hanging

### What is Expected?

Successful connection to socket.io server and successful requests.

- When disabling `xssValidator` option, it works.
- when enabling the option, but with only `GET` requests it works as well.

### What is actually happening?

POST requests never end.

### Notes

I don't know if those options are required for the project to work

```ts
security: {
  contentSecurityPolicy: {
    'connect-src': [
      '\'self\'',
      'ws:',
      'wss:',
    ],
  },
}
```

**Comment by Baroshem** [comment]
Hey,

Thanks for reporting this issue. XSS validator works for both Get and Post requests so probably it is cataching the request and cannot parse it properly. Do you maybe have access to the logs of your app to see if it says something in the console?

**Comment by noook** [comment]
There is no relevant log regarding this issue. I already digged in your module and tried to do some early returns in the `xssValidator` middleware and everything seems "ok", I can't figure out what's happening. It reaches properly the end of the middleware with no error inbetween. 

Can you reproduce with my link ? I tried to provide a reproduction as minimal as possible, with the alternatives where it is working

**Comment by Baroshem** [comment]
Thanks for the additional digging!

Yes, it could be related to that. Would you be interested in creating a Pull Request with a fix for that? I think we would need to support a new case of sockets that wasn't handled before as we were working with pure http requests with body, then we added the multipart form data and today we would also need to support a new case of sockets :)

I could provide all the help needed 🚀

**Comment by noook** [comment]
Of course! My repository exists for this very exact reason

**Comment by GalacticHypernova** [comment]
@noook @Baroshem a little update on this:
This issue is unrelated to the module, but rather directly in h3, so in here nothing needs to be changed unless we want to make a custom method of parsing request body.

**Comment by noook** [comment]
Mentioning the code with this permalink:

https://github.com/unjs/h3/blob/58e33ff00b1db1cf86a780bf8b152c3f7e573350/src/utils/body.ts#L78-L88

Are you suggesting a fix would be to store the result of the promise in a variable attached to the event, so that it can be read again later on ?

I could open an issue for that and eventually provide the fix.

**Comment by GalacticHypernova** [comment]
Well, the issue is not really there, it's in the second promise with bodyData array. I'm experimenting with it to figure out how this could work

**Comment by Baroshem** [comment]
Great @GalacticHypernova that you have found it. I think you could talk with Pooya about it :)

**Comment by GalacticHypernova** [comment]
I think we should, though it's definitely interesting why websockets (or at least this specific websocket) can't use data to read. Ideally it shouldn't do it. I'm not even sure it is an h3 issue. Theoretically it could be an issue of the websocket library itself,  I'll try a different websocket and see

**Comment by Baroshem** [comment]
Closing the issue. If there is a need, please reopen or create a new one :)

**Comment by GalacticHypernova** [comment]
So sorry, got caught up with real life and forgot about this. I think it's definitely not something that needs fixing here though because that would be a workaround rather than an issue. Last I checked I didn't receive a response on the issue I opened in h3 about this, but hopefully when it gets fixed it resolves it for socket as well
