### ISSUE TITLE
Fails with the latest Nuxt

### ISSUE THREAD

**Issue by hermes85pl** [Baroshem/nuxt-security#474]
### Version

nuxt-security: 2.0.0-rc.6
nuxt: 3.12.1

### Reproduction Link

https://stackblitz.com/edit/nuxt-starter-dijohg?file=nuxt.config.ts

### What is Expected?

🚀

### What is actually happening?

```
ERROR [nitro] [unhandledRejection] Cannot destructure property 'headers' of 'securityOptions' as it is undefined.
  at <anonymous> (node_modules/.pnpm/nuxt-security@2.0.0-rc.6_rollup@4.18.0/node_modules/nuxt-security/dist/runtime/nitro/plugins/00-routeRules.mjs:17:11)
  at createNitroApp (node_modules/.pnpm/nitropack@2.9.6_@opentelemetry+api@1.9.0_encoding@0.1.13/node_modules/nitropack/dist/runtime/app.mjs:143:7)
  at <anonymous> (node_modules/.pnpm/nitropack@2.9.6_@opentelemetry+api@1.9.0_encoding@0.1.13/node_modules/nitropack/dist/runtime/app.mjs:151:25)
  at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
  at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
  at async loadESM (node:internal/process/esm_loader:28:7)
  at async handleMainPromise (node:internal/modules/run_main:113:12)
```

**Comment by Baroshem** [comment]
Hey, 

It seems that latest version of Nuxt has a breaking change for the module authors. J will check it out and let you know

**Comment by Baroshem** [comment]
@danielroe were there any changes in terms of how the routeRules are registered in the latest version of Nuxt? It seems to be breaking there

**Comment by Baroshem** [comment]
Daniel will create a patch for Nuxt to resolve this :)

**Comment by GalacticHypernova** [comment]
Oddly enough I can't seem to produce it in the playground. @hermes85pl are you able to provide a stackblitz reproduction? If I can replicate the behavior I could maybe open a patch even sooner (that and I'm curious to actually see it in action)

**Comment by danielroe** [comment]
I'll absolutely look into this. As @GalacticHypernova says, however, I do need a reproduction 🙏

**Comment by hermes85pl** [comment]
It looks like this happens when you throw Turnstile in the mix.

https://stackblitz.com/edit/nuxt-starter-dijohg?file=nuxt.config.ts

**Comment by GalacticHypernova** [comment]
@Baroshem @danielroe after looking around, the issue appears to be that "security" is not present in the nitro routeRules configuration:

![image](https://github.com/Baroshem/nuxt-security/assets/92037085/d2fb6b9d-d3d4-4521-95a7-2b7cc423e2dd)


The thing that causes the issue is this part:
![image](https://github.com/Baroshem/nuxt-security/assets/92037085/6701e398-1358-45ba-af46-29fa79d47c3d)

I have a good feeling (unconfirmed yet) that removing L969 and changing L971 to the following will solve the issue
```ts
const { headers: headers2 } = rules
```

Has the security key been omitted on Nuxt's end or this module's end?

**Comment by Baroshem** [comment]
![image](https://github.com/Baroshem/nuxt-security/assets/37120330/1bc7cdcf-b8b3-4d3e-bd05-ac3b02f984bd)

**Comment by hermes85pl** [comment]
I confirm that I can no longer reproduce the issue after updating to Nuxt v3.12.2 that contains the aforementioned fix.
