### ISSUE TITLE
Defaul CSP crashing site for scripts injected after hydration

### ISSUE THREAD

**Issue by moshetanzer** [Baroshem/nuxt-security#480]
### Version

nuxt-security: 
nuxt: 

### Reproduction Link
Hi,

For some reason it seems like scripts being injected after hydration are crashing site due to hash mismatch with csp default settings? does this make sense?

**Comment by vejja** [comment]
It doesn't make sense if you inject scripts with our recommended method which is `useScript`, or alternatively `useHead`.
Can you share a bit more details on how you inject scripts after hydration ?

**Comment by moshetanzer** [comment]
https://github.com/Baroshem/nuxt-security/issues/482

Misdiagnose. But the above is exaclty my issue
