### ISSUE TITLE
Inline script detection fails when newline is inside script

### ISSUE THREAD

**Issue by Gerbuuun** [Baroshem/nuxt-security#482]
### Version

nuxt-security: 2.0.0.rc6
nuxt: 3.12.2

### Steps to reproduce

- Add `@nuxtjs/color-mode` and `nuxt-security` modules
- enforce strict CSP
- Prerender the page

### What is Expected?
The injected `color-mode` script also receives a hash during SSG

### What is actually happening?
The regexp responsible for detecting scripts does not detect the `color-mode` script because it has a newline character at the end.
See my comments here: https://github.com/nuxt-modules/color-mode/issues/266 (and PR https://github.com/nuxt-modules/color-mode/pull/268)

This behavior will break `@nuxt/ui` and `@nuxt/ui-pro` in SSG because it uses `@nuxtjs/color-mode`.

**Comment by vejja** [comment]
Think PR #478 will fix

**Comment by Baroshem** [comment]
Merged the PR that was supposed to resolve it. @Gerbuuun could you check if with the newest version of the module the problem is still there? :)

**Comment by Gerbuuun** [comment]
@Baroshem Yes, it definitely works now! A hotfix has also been pushed to `@nuxtjs/color-mode` but not yet released.

**Comment by Baroshem** [comment]
Awesome, thanks for leeting me know :)
