### ISSUE TITLE
Use pgk.pr.new

### ISSUE THREAD

**Issue by Baroshem** [Baroshem/nuxt-security#489]
### Describe the solution you'd like

https://github.com/stackblitz-labs/pkg.pr.new

**Comment by vejja** [comment]
Would love to get this running
@Baroshem - you just need to install the Github app, I can take care of the rest if you want

By the way, Nuxt Core now also uses these:
- CodeRabbitAI
- SocketSecurity

**Comment by Baroshem** [comment]
Hey @vejja 

This is a great idea! Do we actually need to install the GitHub app? I wasn't able to find any info about it but instead a Github action script https://github.com/stackblitz-labs/pkg.pr.new?tab=readme-ov-file#release-each-commit-and-pull-request

Maybe we could use that?

Regarding other things, CodeRabbitAI and SocketSecurity, I am not familiar with these tools. Do you think we should add them?

**Comment by vejja** [comment]
On pkg.pr.new, I think they say in their README that you need to install the Github app first, before you can use the action script. But maybe I'm wrong.
On the other two, I don't think it's urgent. I tend to find that CodeRabbit helps reading PRs, but on the other hand it generates a lot of verbose comments. Maybe you want to wait a bit more and get some feedback from the Nuxt Core team if they think it is useful. SocketSecurity looks like dependabot on steroids - we already have dependabot so it's not a must-have I would say.

**Comment by Baroshem** [comment]
I must have missed this point in the docs. Installed it now!

Regarding the other two, let's wait for further adoption :)
