### ISSUE TITLE
when `corsHandler.origin` is `RegExp[]`, it doesn't work

### ISSUE THREAD

**Issue by Shana-AE** [Baroshem/nuxt-security#497]
### Version

nuxt-security: v2.0.0-rc.9
nuxt: v3.12.4

### Reproduction Link

![image](https://github.com/user-attachments/assets/7f7df473-96da-4bb0-93bf-1c254e165503)

![image](https://github.com/user-attachments/assets/a8d5819a-836b-467e-a009-e84ace5be838)

`useRuntimeConfig` retrieve runtimeConfig from `process.env` which made `RegExp` inside `origin` be `JSON.stringify`ed to `{}`, so `corsHandler.origin` `RegExp[]` is not available now.

### What is Expected?
it should work
### What is actually happening?
when `corsHandler.origin` is `RegExp[]`, it doesn't work

**Comment by Baroshem** [comment]
Hey @Shana-AE I needed to revert this change as we are not sure what do to about the serializaiton/deserialization issue :(

**Comment by Shana-AE** [comment]
> Hey @Shana-AE I needed to revert this change as we are not sure what do to about the serializaiton/deserialization issue :(
> 
> More details [#492 (comment)](https://github.com/Baroshem/nuxt-security/pull/492#issuecomment-2277645057)

Ok, you can revert it as you wish :)
I just want to solve the problem and let it be solved as perfect as possible. and I'm not confident with this solution. If you have any other solution, just please let me know and show me the solution to let me improve myself. :)
and I also replied at https://github.com/Baroshem/nuxt-security/pull/492#issuecomment-2278008146 :) please check it:)

**Comment by P4sca1** [comment]
@Shana-AE This should be fixed with https://github.com/Baroshem/nuxt-security/pull/509.
Note that you need to pass regular expressions as strings and enable `corsHandle.useRegExp`.

**Comment by Baroshem** [comment]
Released in 2.0.0 :)
