### ISSUE TITLE
Nonce generation fails on cloudflare

### ISSUE THREAD

**Issue by dirksierd** [Baroshem/nuxt-security#510]
### Version

nuxt-security: 2.0.0-rc.9
nuxt: 3.12.4

### Reproduction Link

- https://github.com/dirksierd/nuxt-csp-test
- https://nuxt-csp-test.pages.dev/

### Steps to reproduce

I created a new project and added the security module. Pushed to repo and deployed in the Cloudflare dashboard.

### What is Expected?

I’d expect to see unique nonces on each request.

### What is actually happening?

I only see the same nonce everywhere, on each request: `AAAAAAAAAAAAAAAAAAAAAA==`

I tried adding the node_compat flag, or changing the node-version, to no avail. Presumably [this call to randomBytes()](https://github.com/Baroshem/nuxt-security/blob/2d5128244e3c53ecc100cdca41e45f593ec086c4/src/runtime/nitro/plugins/40-cspSsrNonce.ts#L23) doesn’t work as expected on cloudflares’ end. It does work when building and running locally.

**Comment by vejja** [comment]
Hi @dirksierd 
I’m surprised because the official cloudflare docs say that randomBytes is officially supported in workers : https://developers.cloudflare.com/workers/runtime-apis/nodejs/crypto/#:~:text=The%20node%3Acrypto%20module%20provides,module%20is%20available%20in%20Workers.

Can you verify your Cloudflare setup?

**Comment by dirksierd** [comment]
For the aforementioned pages-link I made a new project without any modifications. Have been tinkering with the cloudflare-settings, for ages, on the project that led me to this bug report.

I’m afraid I’m out of options.

**Comment by vejja** [comment]
Sorry to ask, did you follow instructions at
https://nuxt.com/deploy/cloudflare

With command set to build ?

**Comment by dirksierd** [comment]
That's the default setting, and it says so in the build log. that `nuxt build` is running.

I'm starting to think that maybe the `node_compat`-flag is not registering somehow.
I tried running a different crypto-method (said to be working in Cloudflare-docs) and it threw an exception.

**Comment by vejja** [comment]
Hmm
I’m no Cloudflare expert but you sound right
Other users deploying on Cloudflare didn’t report any issue in the past though.

However this type of report might be a good opportunity for us to move from node:crypto to the WebCrypto API. Would be good if you can test whether getRandomValue would return something useful in your api route 🙏

**Comment by dirksierd** [comment]
I've been digging some more, and feel like I'm forced to use unenv-polyfills.
I tried running the `getChipers`-method too, which threw the NotImplemented-exception.

https://github.com/unjs/unenv/blob/main/src/runtime/node/crypto/internal/node.ts

Not sure yet on how to trick unenv into using its cloudflare-preset, which, I feel, will solve the issue.

**Comment by dirksierd** [comment]
Allright that fixed it… <https://github.com/dirksierd/nuxt-csp-test/blob/main/nuxt.config.ts>
Not sure on how to move forward with this issue now, though.

**Comment by vejja** [comment]
Looks like a complex setup for the average nuxt.config.ts
- security.enabled is true by default
- The preset is at nitro: { preset : ‘…’ }

**Comment by dirksierd** [comment]
Sure but I’ve got https-issues in development, so disabled then.

And the nitro preset is something else, I believe, that in turn uses an unenv-preset under the hood that I can’t set to something else unless by importing like in the linked nuxt-config.
