### ISSUE TITLE
Do nothing if module deactivated

### ISSUE THREAD

**Issue by zakarialounes** [Baroshem/nuxt-security#511]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `nuxt-security@2.0.0-rc.9` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/nuxt-security/dist/module.mjs b/node_modules/nuxt-security/dist/module.mjs
index 26bf61b..425990b 100644
--- a/node_modules/nuxt-security/dist/module.mjs
+++ b/node_modules/nuxt-security/dist/module.mjs
@@ -16,6 +16,9 @@ const module = defineNuxtModule({
     configKey: "security"
   },
   async setup(options, nuxt) {
+    if (options.enabled || nuxt.options.security?.enabled || nuxt.options.runtimeConfig.security?.enabled || false) {
+      return;
+    }
     const resolver = createResolver(import.meta.url);
     nuxt.options.build.transpile.push(resolver.resolve("./runtime"));
     const strict = options.strict || nuxt.options.security?.strict || nuxt.options.runtimeConfig.security?.strict || false;
@@ -39,9 +42,6 @@ const module = defineNuxtModule({
       }
     );
     const securityOptions = nuxt.options.runtimeConfig.security;
-    if (!securityOptions.enabled) {
-      return;
-    }
     if (securityOptions.removeLoggers) {
       addVitePlugin(viteRemove(securityOptions.removeLoggers));
     }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by vejja** [comment]
Hi @zakarialounes 
Can you tell me a little bit more about the issue you encountered?
I can’t really see which fundamental change the patch would introduce. Let us know !
Best

**Comment by zakarialounes** [comment]
Hello and thank you for your message @vejja even though I closed the issue.

I'm still investigating, but I can say that using nuxt-security prevents nuxt-highcharts from working properly (although supposedly not compatible with nuxt3, I've managed to get it to work for a long time, except since adding the nuxt-security module).

**Comment by zakarialounes** [comment]
Ok I was able to find the source of the problem. 

If you have the following vite configuration (please see below) then `removeLoggers` doesn't work and prevents nuxt-highcharts from working.

```js
{
  build: {
    terserOptions: {
      compress: {
        drop_console: true,
        drop_debugger: true,
      },
    },
  },
}
```

**Comment by vejja** [comment]
Ok thanks @zakarialounes for the info

@Baroshem maybe we could replace Talljack’s plugin by the native drop_console option of Vite?

**Comment by Baroshem** [comment]
@vejja We could do so but we would need to wait for the next major version as I would like to avoid shipping breaking changes in minor or patch.

Could we plan it for 3.0.0!?
