### ISSUE TITLE
CPS for SPA using vuetify

### ISSUE THREAD

**Issue by JoBabble** [Baroshem/nuxt-security#512]
We are encountering issues with our Content Security Policy (CSP) configuration in our Nuxt 3 application. Specifically, inline styles are being blocked by the CSP, and the following error messages are appearing in the console:

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' . Either the 'unsafe-inline' keyword, a hash ('sha256-NnJxHlvTEEiumDmjGQ0VaN6pvuqDnlZBbLNuuQPg1Hk='), or a nonce ('nonce-...') is required to enable inline execution.

The issue is related to the fact that the inline styles are not being accepted due to the current CSP configuration which only allows styles from 'self', and specific hashes/ https

My config: 

```
security: {
    headers: {
      contentSecurityPolicy: {
        "base-uri": ["'none'"],
        "default-src": ["'none'"],
        "connect-src": ["'self'", "https:"],
        "font-src": ["'self'"],
        "form-action": ["'self'"],
        "frame-ancestors": ["'self'"],
        "frame-src": ["'self'"],
        "img-src": ["'self'", "https://a.storyblok.com"],
        "manifest-src": ["'self'"],
        "media-src": ["'self'"],
        "object-src": ["'none'"],
        "script-src-attr": ["'none'"],
        "style-src": [
          "'self'",
          "https:",
         
          // "'unsafe-inline",  if enabled all fine
        ],
        "script-src": [
          "'self'",
          "'strict-dynamic'",
          "'nonce-{{nonce}}'",
          "https:",
        ],
        "upgrade-insecure-requests": true,
        "worker-src": ["'self'"],
      },
    },
  },

```

I use nuxt 3.12.4  in SPA Mode with Vuetify.
What would be the next step?. I'm not entirely sure if you support even SPAs since the docs talk about SSG.
Interestingly the error comes from client.ts

**Comment by vejja** [comment]
Hi @JoBabble 
Your SPA can work with Nuxt-Security, but you will have to use ‘unsafe-inline’ on style-src. Please note that this is our default value.

Unfortunately this is a limitation that all SPAs have with CSP (this is even beyond Nuxt), and it is related to the fact that Vuetify is probably trying to modify your inline styles dynamically via Javascript from the client-side. There is nothing we can do about this as it is part of the CSP specification: prevent all inline styles modifications by the client, except if you use ‘unsafe-inline’.

We have a pretty detailed explanation on how CSP works with styles [here](https://nuxt-security.vercel.app/documentation/advanced/strict-csp#nonces-and-hashes-csp-level-2) if you want to read more.
Cheers

**Comment by Baroshem** [comment]
Great explanation by @vejja !

This is how CSP works for SPA's unfortunately. I hope that the detailed info from Sebastien will help you understand how it works in NuxtSecurity :)

**Comment by JoBabble** [comment]
> Hi @JoBabble Your SPA can work with Nuxt-Security, but you will have to use ‘unsafe-inline’ on style-src. Please note that this is our default value.
> 
> Unfortunately this is a limitation that all SPAs have with CSP (this is even beyond Nuxt), and it is related to the fact that Vuetify is probably trying to modify your inline styles dynamically via Javascript from the client-side. There is nothing we can do about this as it is part of the CSP specification: prevent all inline styles modifications by the client, except if you use ‘unsafe-inline’.
> 
> We have a pretty detailed explanation on how CSP works with styles [here](https://nuxt-security.vercel.app/documentation/advanced/strict-csp#nonces-and-hashes-csp-level-2) if you want to read more. Cheers

Dear Sebastian, thank you very much for the details. This helps us a lot :)
