### ISSUE TITLE
Cheerio released a new version that broke nuxt security

### ISSUE THREAD

**Issue by cesxhin** [Baroshem/nuxt-security#513]
### Version

nuxt-security: 1.4.3
nuxt: 3.12.4

### Reproduction Link
https://codesandbox.io/p/devbox/weathered-brook-g3klnn

### Steps to reproduce
clear folder node_modules and file package-lock.
Install packages and start project nuxt.

### What is Expected?
The project start correctly.

### What is actually happening?
The path of the internal library [cheerio](https://github.com/cheeriojs/cheerio/releases/tag/v1.0.0) is changed from "cheerio/lib/slim" to "cheerio/slim" with version package v1.0.0.

**Comment by markus-gx** [comment]
@cesxhin 
Since `cheerio` is entirely removed in Version 2 RC.1 (we are at RC.7 now) (https://github.com/Baroshem/nuxt-security/releases/tag/v2.0.0-rc.1) you could resolve this via a resolution in your package.json: 

```
  "resolutions": {
    "cheerio": "1.0.0-rc.12"
  }
```
