### ISSUE TITLE
CSP fails with strict-dynamic when implementing Cloudflare Web Analytics

### ISSUE THREAD

**Issue by adamdehaven** [Baroshem/nuxt-security#546]
When following the `@nuxt/scripts` implementation instructions for Cloudflare Web Analytics here: https://scripts.nuxt.com/scripts/analytics/cloudflare-web-analytics (the "Loading Globally" section, as well as "useScriptCloudflareWebAnalytics" my CSP settings are consistently producing the following error:

```md
Refused to load the script 'https://static.cloudflareinsights.com/beacon.min.js' because it
violates the following Content Security Policy directive: 
"script-src 'self' https: 'unsafe-inline' 'strict-dynamic' 'unsafe-eval' ...[a bunch of sha]".
Note that 'strict-dynamic' is present, so host-based allowlisting is disabled. 
Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

Here's my `nuxt.config.ts` entry for the module:

```ts
security: {
  headers: {
    crossOriginEmbedderPolicy: 'unsafe-none',
    crossOriginOpenerPolicy: false, // Resolves a NS_ERROR_FAILURE error in Firefox
    xFrameOptions: 'SAMEORIGIN',
    contentSecurityPolicy: {
      'upgrade-insecure-requests': import.meta.env.NODE_ENV === 'development' ? false : true, 
      'img-src': ["'self'", 'data:', 'https:'],
      'frame-ancestors': ["'self'", 'localhost:*', 'http://localhost:*', 'https://localhost:*', 'https://*.example.com'],
      'script-src': [
        "'self'",
        'https:',
        "'unsafe-inline'",
        "'strict-dynamic'",
        "'nonce-{{nonce}}'",
        "'unsafe-eval'",
      ],
      'script-src-attr': ["'self'"],
      'style-src': [
        "'self'", 
        'https:',
        "'unsafe-inline'",
      ],
    },
  },
  rateLimiter: false,
  removeLoggers: false,
}
```

According to the [Nuxt security docs on whitelisting external resources](https://nuxt-security.vercel.app/documentation/advanced/strict-csp#whitelisting-external-resources) utilizing `useScript` (or the global loader, I'm assuming) should bypass this issue because of the `strict-dynamic` rule.

If I remove `strict-dynamic` from my config, the issue is resolved, but this isn't ideal.

What am I doing wrong? Any help would be appreciated.

**Comment by vejja** [comment]
Hi @adamdehaven 
Can you tell me
- how you load Cloudflare Web Analytics with the global loader (nuxt.config.ts entry)
- how you use `useScript` (unfortunately there are 2 different useScript: the one from `unhead`, and the one from `@nuxt/scripts`)
- how you deploy (static or SSR)

Thanks

**Comment by adamdehaven** [comment]
`useScript` is available from the `@nuxt/scripts` install

> * how you deploy (static or SSR)

I have two sites with the same issue. One is build with `cloudflare-pages-static` Nitro preset (so, `static`), and the other with `cloudflare-module` preset (SSR).

> * how you load Cloudflare Web Analytics with the global loader (nuxt.config.ts entry)

I actually tried a few different ways.

Via the `nuxt.config.ts`:

```ts
$production: {
  scripts: {
    registry: {
      cloudflareWebAnalytics: true,
    },
  },
}
```

And then separately, I also tried using the composable in `app.vue` in the root of the `script setup` block:

```ts
const { token } = useRuntimeConfig().public.scripts.cloudflareWebAnalytics
if (token) {
  useScriptCloudflareWebAnalytics({
    token,
    scriptOptions: {
      trigger: 'onNuxtReady',
    },
  })
}
```

**Comment by vejja** [comment]
In the raw HTML that you get on your home page, can you see the `https://static.cloudflareinsights.com/beacon.min.js` script src somewhere ?

**Comment by adamdehaven** [comment]
Yes:

```html
<script data-onload="" data-onerror="" defer="" fetchpriority="low" referrerpolicy="no-referrer" src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon="{&quot;token&quot;:&quot;<TOKEN>&quot;,&quot;spa&quot;:true}" data-hid="136af0b"></script>
```

**Comment by vejja** [comment]
The script is being inserted server-side, this is incompatible with CSP. Which causes the error.

There seems to be an option for ´client’ mode with the composable : https://scripts.nuxt.com/scripts/analytics/cloudflare-web-analytics#usescriptcloudflarewebanalytics

but it’s not 100% clear to me how to disable server-side injection from reading the docs

I’m offline right now and cannot assist better immediately I’m afraid. Maybe you can ask the team @nuxt/scripts why the script is being inserted server-side, they will know

copying @harlan-zw on this one

**Comment by adamdehaven** [comment]
I was able to get this working by utilizing [`useHead`](https://nuxt.com/docs/api/composables/use-head) (available directly in Nuxt, without the need for `@nuxt/scripts`.

I simply placed this into my `app.vue` at the project root:

```typescript
useHead({
  script: [{
    src: 'https://static.cloudflareinsights.com/beacon.min.js',
    'data-cf-beacon': JSON.stringify({
      token: '<TOKEN>',
      spa: true,
    }),
    defer: true,
    tagPosition: 'bodyClose',
    key: 'cloudflare-web-analytics',
  }],
}, { mode: 'client' })
```

---

@harlan-zw I attempted multiple solutions with `@nuxt/scripts` (and the `useScriptCloudflareWebAnalytics` composable), even trying to pass `trigger: 'client'` and a couple other variations; however, it never seemed to respect the config setting. 

---

Separately, @vejja this required a manual setup (i.e. manually loading the script here) in Cloudflare; however, they also have an "automated setup" where they simply inject the HTML into the site.

With the `strict-dynamic` rule in place, their added script tag is still subject to the original error in this Issue. Is there a workaround in my CSP settings if I want to allow an "integration" (e.g. Cloudflare Web Analytics) to add its own script on the page without requiring this manual setup?

**Comment by vejja** [comment]
If the script src tag is delivered as part of the original HTML, it will be denied by CSP. This is the whole point of CSP.

However if the script src tag is added dynamically by the client after the original HTML is received, it will be allowed - provided the ‘strict-dynamic’ policy is set and the ‘useHead’ or ´useScript’ composables are used to insert the script. 

So : if anyone injects the <script> tag directly in the original HTML response, it will fail. There is no way around this.

**Comment by vejja** [comment]
What was the solution eventually @adamdehaven ?
We may want to clarify this in our docs

**Comment by adamdehaven** [comment]
I used the implementation mentioned above [here](https://github.com/Baroshem/nuxt-security/issues/546#issuecomment-2465843957) 

I was waiting to hear back from Harlan to determine if respecting the client settings in `@nuxt/scripts` is a valid bug (then I can open an issue over there and maybe push a patch)

**Comment by harlan-zw** [comment]
You can see a demo here: https://scripts-phi.vercel.app/third-parties/cloudflare-web-analytics/nuxt-scripts. The script is not within the SSR Response.

However, maybe it's the preloading causing the issue?

```html
<link fetchpriority="low" as="script" referrerpolicy="no-referrer" href="https://static.cloudflareinsights.com/beacon.min.js" rel="preload">
```

I added this to make sure the script gets loaded as fast as possible but maybe it's causing issues. We can configure this behavior with `warmupStrategy`:

```ts
useScriptCloudflareWebAnalytics({
  token: '<token>',
  scriptOptions: {
    warmupStrategy: false, 
  }
})
```

Maybe we need to set this as the default if Nuxt Security is used?

**Comment by vejja** [comment]
@harlan-zw I need to double check whether rel=preload would be an issue, I don’t think it should

what striked me here is OP was saying the script was in the server response

@adamdehaven this is weird. You should have been able to use @nuxt/scripts out of the box without any custom code.

Would you mind sending a screenshot of the HTML portion where the script appears, as well as a screenshot of the CSP denial message in the console - in both cases trying to make sure the line numbers match? This would be helpful in trying to understand the potential relationship with the preload link

**Comment by adamdehaven** [comment]
I also tried implementing this code block twice: one iteration with all the settings shown, and one where I excluded the `scriptOptions.trigger`.

```ts
useScriptCloudflareWebAnalytics({
  token: '<token>',
  scriptOptions: {
    trigger: 'onNuxtReady',
    warmupStrategy: false,
  },
})
```

The preload script is still injected into the head in both scenarios causing the CSP error. 

I think there may be an issue internally with `@nuxt/scripts`? It doesn't seem to be respecting the warmupStrategy as I would expect the preload link to not be inserted

**Comment by adamdehaven** [comment]
If I'm [quickly] reading [this block from `useScripts`](https://github.com/nuxt/scripts/blob/c6831d74135e190007afceda5c76f76bb3e6f6f4/src/runtime/composables/useScript.ts#L65-L67) correctly, it appears that if I set `options.warmupStrategy` to `false`, it's **always** setting it to `preload` which in this case, I think isn't desired? @harlan-zw check me here
