### ISSUE TITLE
The default behavior of `removeLoggers` is not correctly documented

### ISSUE THREAD

**Issue by guenbakku** [Baroshem/nuxt-security#570]
### Version

nuxt-security: 2.1.4
nuxt: 3.14.1592

### Reproduction Link

Blank project without `removeLoggers` specified or set to `true`
```ts
// nuxt.config.ts
export default defineNuxtConfig({
  security: {},
  // or 
  // security: { removeLoggers: true },
});
```

### Steps to reproduce

Configure the `nuxt.config.ts` like above and access to nuxt app in production mode.  
(In my case, i used `nuxt generate` to generate a static site)

### What is Expected?

Only the `log` and `debug` logger are removed as described in the document: 
> Fortunately, nuxt-security module removes both `log` and `debug` console outputs by default so your application is not leaking this information.
> ref: https://nuxt-security.vercel.app/documentation/utils/remove-console-loggers#:~:text=nuxt%2Dsecurity%20module%20removes%20both%20log%20and%20debug

### What is actually happening?

All the loggers (included `warn` and `error`) are removed.

**Comment by vejja** [comment]
Hi @guenbakku
Your are right
This is a documentation issue. All `console.*` are removed in v2.1+
Our docs are lagging a bit, they will get back in sync once we merge #560

**Comment by guenbakku** [comment]
Hi @vejja  
Thanks for your quick reply. I got it!
