### ISSUE TITLE
Module problem on Windows

### ISSUE THREAD

**Issue by skyproboost** [Baroshem/nuxt-security#60]
Is it possible to fix the absolute path problem on windows?

Build error: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

**Comment by Baroshem** [comment]
Hey, 

This is a problem of Nitro plugins that we are discussing here 

For now, you can set the `hidePoweredBy: false` in your security configuration and you should be fine.
