### ISSUE TITLE
Can we access the default middleware options for headers to prevent errors in dev mode?

### ISSUE THREAD

**Issue by ymansurozer** [Baroshem/nuxt-security#70]
Is there a way to access the default headers used by the module? It is a pain to deal with SSL and other errors during dev mode, and it would be great if we could do something like this:

```
// nuxt.config.ts
security: {
  headers: process.dev ? false : defaultHeaders
}
````

**Comment by Baroshem** [comment]
Hey, not really. The default value is set after registering the module so it is not possible to have access to these headers like this.

You can always register the whole module on prod environment only in a similar manner as you described in the issue, i.e conditionally add to an array of modules this nuxt-security module when it is in prod environment.

**Comment by ymansurozer** [comment]
Thanks! I see, that makes sense. Except I need to set hidePoweredBy to false for this issue: https://github.com/Baroshem/nuxt-security/issues/60. I'll try to find a way.

As a humble feature request: It would be great to have an option to not register the module during dev mode. That would simplify things a lot.

**Comment by Baroshem** [comment]
I dont think that not registering a module in dev is a good thing. Instead, I would recommend to add a configuration option `enabled` that when set to false will disable the module completely. This way, you could add a condition there that if it is a dev env then enabled will be false and if prod env it will be true. This will give you the functionality you need and wont disable the module for everyone else.

Let me know what you think about it and I will add it :)

**Comment by ymansurozer** [comment]
That would be perfect actually. :) Thanks for your help Jakub, much much appreciated.
