### ISSUE TITLE
Add a default `default-src` directive for Content Security Policy?

### ISSUE THREAD

**Issue by flauwekeul** [Baroshem/nuxt-security#86]
### Is your feature request related to a problem? Please describe.

When the `default-src` directive isn't present and a directive isn't specified, everything is allowed (in some cases) for that unspecified directive (according to the answers [here](https://security.stackexchange.com/questions/240445/what-is-the-behaviour-of-csp-if-default-src-not-specified)).

In the [default values for the CSP header](https://nuxt-security.vercel.app/middlewares/headers#content-security-policy), there is for example no [`media-src`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/media-src) directive and no `default-src`. It is my understanding that anything is allowed for `media-src`.

### Describe the solution you'd like

Add a default value for the `default-src` directive. Something like:
```ts
'default-src': ["'self'"]
```

### Describe alternatives you've considered

An alternative could be to add default values for all directives. But I still think it's good to have a `default-src` in case directives are added in the future.

### Additional context

N/A.

**Comment by Baroshem** [comment]
Hey, 

Thanks for creating this issue. I will take a look at it in the upcoming days :)

**Comment by Baroshem** [comment]
Hey @flauwekeul 

I have tested this out and due to how Nuxt is build with Vite, when adding this directive, following errors are appearing in the console:

![image](https://user-images.githubusercontent.com/37120330/215072799-56bf79c8-292c-4d70-840b-250eb3d7e2f0.png)

Because of that, I dont think that we can include this in the module (tested both on dev and prod environments). If you have any other idea on how this could be solved, please let me know

**Comment by Baroshem** [comment]
You are right. I have not added them last time.

But I just added them now and the error is different:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/37120330/215759942-c51ff65d-e4b2-445e-9145-69ade219229a.png">

Does it work for you?

**Comment by flauwekeul** [comment]
That's probably because of https://github.com/nuxt/nuxt/issues/11793 😞

You could update the default `contentSecurityPolicy` header to this:

```ts
contentSecurityPolicy: {
  value: {
    'base-uri': ["'self'"],
    'connect-src': ["'self'", ...(process.env.NODE_ENV === 'production' ? [] : ['ws://localhost:*'])],
    'default-src': ["'self'"],
    'font-src': ["'self'", 'https:', 'data:'],
    'form-action': ["'self'"],
    'frame-ancestors': ["'self'"],
    'img-src': ["'self'", 'data:'],
    'object-src': ["'none'"],
    'script-src-attr': ["'none'"],
    'style-src': ["'self'", 'https:', "'unsafe-inline'"],
    'upgrade-insecure-requests': true
  },
  '/**'
}
```

That should give no errors with a default Nuxt app in both development and production. Those `"'unsafe-inline'"` can be removed once that issue is fixed.

**Comment by Baroshem** [comment]
Hey @flauwekeul 

Sorry for no contact from my side. I wqs busy with other tasks recently. This sounds reasonable. I will check it out in the upcoming days and see if this could be included in the next release of the module :)

**Comment by flauwekeul** [comment]
Sure. I'll give it a try 👌

**Comment by Baroshem** [comment]
Hey, any news?

**Comment by flauwekeul** [comment]
Sorry, been busy with other things. I'll try something this week, else you can just close it.

**Comment by flauwekeul** [comment]
The solution we have at my client is adding the `'unsafe-inline'` value, but that's only because Nuxt 3 [doesn't support](https://github.com/nuxt/nuxt/issues/11793) generating hashes or nonces yet (I see you also commented in that issue). I don't think adding `'unsafe-inline'` as a default value in a module that's supposed to improve security is a good idea. It should be up to your users to make that decision.

So, until that issue is fixed, it's probably better not to add a `default-src` directive.

**Comment by Baroshem** [comment]
Ok @flauwekeul 

Thanks for verifying that and letting me know.
