### ISSUE TITLE
Issue on Nuxt v3.1.1 

### ISSUE THREAD

**Issue by Loyz07** [Baroshem/nuxt-security#89]
Hello,

A little issue with Nuxt v3.1.1...

### Version

nuxt-security: v0.10.1
nuxt: v3.1.1

### Reproduction Link

[Stackblitz](https://stackblitz.com/edit/nuxt-starter-ugbdvj?file=nuxt.config.ts)

### Steps to reproduce

Install the module and add it to nuxt.config.ts

### What is Expected?

The module to works 😇

### What is actually happening?

An error and blank page on Stackblitz.

On my local the error is:

[worker reload] [worker init] Cannot find package '@nozomuikuta/h3-cors' imported from /Users/lguegu50/projects/dkt/corength/platform/webapp/.nuxt/dev/index.mjs     17:20:58

  at new NodeError (node:internal/errors:371:5)
  at packageResolve (node:internal/modules/esm/resolve:932:9)                                                                                                                17:20:43
  at moduleResolve (node:internal/modules/esm/resolve:978:18)
  at defaultResolve (node:internal/modules/esm/resolve:1080:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
  at link (node:internal/modules/esm/module_job:78:36)

Be the force be with you for that 💪.

**Comment by Baroshem** [comment]
Hey, thanks for reporting this issue! 

I will take a look at it later today. It seems like with the newest version of nuxt there is a different approach for handling packages. I will let check it out and let you know :)

**Comment by Baroshem** [comment]
This is quite strange. 

I have tested it in the module repository with both dev and prod environments on nuxt 3.1.1 and it is working correctly.

BTW, I intentionally not bump the package dep version to not include breaking changes for the current users. I will do this in the next major version of the security module.

When I check the stackblitz you linked, it just does not start for me

**Comment by Baroshem** [comment]
I managed to reproduce it on another stackblitz that I have created but this bug seems to be appearing on stackblitz only. 

Have you encountered this kind of bug in your local/production project?

**Comment by Baroshem** [comment]
In my case. this bug appears also on version 3.0.0 of Nuxt. I have contacted a cors package maintainer about this -> https://github.com/NozomuIkuta/h3-cors/issues/9

**Comment by Loyz07** [comment]
Hello Jakob,

Yes on my local the error is the one I sent in my first message.

**Comment by DamianGlowala** [comment]
I can confirm the exact same error happens in my case (locally) and prevents from using the module. Let me know if there is any additional info I could provide to help find the cause of this issue.

**Comment by Baroshem** [comment]
@DamianGlowala @Loyz07 could you tell me what package manager are you using?

I am always using yarn and in this case, it works correctly. When I switched to npm for a local project, it stopped working for some reason with the error you mentioned.

It seems that for npm this package (maybe it is due to the fact that it starts with `@` in the name) is not added to nuxt dev file. This is really strange. I think I would need to ask someone wiser than me.

@danielroe have you encountered something like this?

**Comment by DamianGlowala** [comment]
It is npm, indeed

**Comment by Baroshem** [comment]
**Summary:**

When using `npm`, the package `@nozomuikuta/h3-cors` is not added to the `.nuxt/dev/index.mjs` and because of that, the error appears.

**Comment by Baroshem** [comment]
**Summary:**

When using `npm` this is the following import in `.nuxt/dev/index.mjs` (it also throws an error)

```ts
import { FilterXSS } from 'file:///Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-app/node_modules/xss/lib/index.js';
import { defineCorsEventHandler } from '@nozomuikuta/h3-cors';
```

And this should be a correct approach (how it works with `yarn`):

```ts
import { FilterXSS } from 'file:///Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-app/node_modules/xss/lib/index.js';
import { defineCorsEventHandler } from 'file:///Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-app/node_modules/@nozomuikuta/h3-cors/dist/index.mjs';
```

**Comment by Baroshem** [comment]
It almost looks like for npm it is failing when a package name starts with `@` because other packages are working correctly (like xss or basic-auth)

**Comment by Baroshem** [comment]
You can disable cors middleware  in the configuration like following and it should make the whole project work (without cors unfortunately but it will work. In the meantime I will work on the fix to make it work with cors middleware)

```ts
export default defineNuxtConfig({
    modules: ['nuxt-security'],
    security: {
      corsHandler: false
    }
})

```

**Comment by Loyz07** [comment]
npm for me too !

**Comment by danielroe** [comment]
cc: @pi0

**Comment by Baroshem** [comment]
@pi0 

Could you please provide here a solution you recommended in DM?

**Comment by Baroshem** [comment]
I got the confirmation from Pooya that this bug is fixed in the next major version of Nuxt. I will bump it and see if it works :)

**Comment by Baroshem** [comment]
The issue is no more on 3.2.0 version of Nuxt. Once the new version of the Security Module will be out, this issue should be fixed as well. Planning to release a new version next week :)

**Comment by pi0** [comment]
Did you migrate to cors  utils from 'h3' ?

**Comment by Baroshem** [comment]
Not yet.

I have been thinking about doing it as a separate issue and to develop it for the next version (like the one after next weeks version) as this is a feature.

But I can also take a look at it to see if this can be migrated easily.

**Comment by Baroshem** [comment]
@pi0 

Is the usage of the cors addition to H3 documented somewhere?

**Comment by Baroshem** [comment]
I have tested the new version of Nuxt Security 0.11.0 with Nuxt 3.2.2 and it seems to be working correctly. I am closing this issue.

If you will still encounter this issue, please let me know so that I can reopen it :)

**Comment by DamianGlowala** [comment]
I have deleted `package-lock.json`, `node_modules`, updated Nuxt to v3.2.3, installed dependencies and yet I can see the same error. I don't have any security config though, just added the `nuxt-security` to the list of modules :)

![image](https://user-images.githubusercontent.com/48835293/222435769-f6328af5-f92e-4989-85f7-5782b9d3597c.png)

**Comment by Baroshem** [comment]
@DamianGlowala have you cleared the .nuxt folder before runing dev again?

**Comment by maxdzin** [comment]
Same for me. I made a clean install as well as cleared the `.nuxt` dir, but that's not helped, The issue still persist:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@nozomuikuta/h3-cors' imported from /app/.nuxt/dev/index.mjs
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap. (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```
So, I resolved this for now by adding this package into the `overrides` section of the package.json:
```
"overrides": {
  "@nozomuikuta/h3-cors": "latest"
}
```

**Comment by Baroshem** [comment]
I see, then please use the solution from @maxdzin or disable `corsHandler` for now. 

In the upcoming weeks I will be migrating the current corsHandler to native H3 cors functionality as the h3-cors package is deprecated (it was actually merged to h3). This will most probably require a change in the cors interface and will allow me to get rid of this package and eventually, fix this problem for your in npm.

Sorry for the trouble but I cannot reproduce this issue on my end with npm but can completely understand that it can happen to you.

Stay tuned!

**Comment by Baroshem** [comment]
This will be released with upcoming 0.12.0 version

**Comment by Baroshem** [comment]
@DamianGlowala @maxdzin @tmlmt @lynxionxs

I have just released the new version where this problem should not appear https://github.com/Baroshem/nuxt-security/releases/tag/v0.12.0

Let me know if it works. I am doing my best to solve those issues but even today I had a H3 related issue that tooked me days to solve :(

**Comment by maxdzin** [comment]
Hi @Baroshem ,
Thank you, it works pretty fine now for Nuxt v3.2.3.

**Comment by Baroshem** [comment]
Awesome! Closing the issue then.

Sorry for the trouble. I am glad that it finally works for you :)

**Comment by coreysyms** [comment]
Confirming v0.12.0 + Nuxt v3.2.3 works!

Just a note for others coming here. you MUST update to Nuxt v3.2.3 or above or you will get an can't find 'h3' error.

**Comment by Baroshem** [comment]
@coreysyms 

Could you please create an issue with explanation of the error you have encountered? I would prefer to provide some kind of backward compatibility so that other users will be protected agains such issues.

I will really appreciate it :)

**Comment by coreysyms** [comment]
Sure thing. I was running standard install of 0.12.0.

```
"devDependencies": {
    "@types/node": "^18.14.2",
    "nuxt": "^3.2.0",
    "nuxt-security": "^0.12.0"
  }
```

Error on npm run build. `syntaxError: The requested module 'h3' does not provide an export named 'handleCors'`

**Comment by Baroshem** [comment]
@coreysyms 

Thanks for the additional info!

I think this bug is caused by the fact that the support for Cors in H3 was added in a major 1.5.0 version of H3 but a bump of H3 version used in Nuxt was done in a patch version. I will add a note in the docs about using cors that if you use a Nuxt in < 3.2.0 you have to use nuxt-security 0.11.0
