### ISSUE TITLE
basicAuth all routers

### ISSUE THREAD

**Issue by productdevbook** [Baroshem/nuxt-security#90]
Can there be an auth structure that will pass completely to all applications and links?

**Comment by Baroshem** [comment]
Hey, I am not sure if I understand the question correctly. Do you mean that you would like to set a basic auth for all routes in your application?

If so, you can do it like following:

```ts
// nuxt.config.js

{
  modules: [
    "nuxt-security",
  ],
  security: {
    basicAuth: {
      route: '', // <- empty string here tells nuxt that this route handler is a global middleware for all routes
      value: {
        name: 'test',
        pass: 'test',
        enabled: true,
        message: 'test'
      }
    }
  }
}
```

If that was not what you were trying to get, please elaborate on your request and I will do my best to answer :)
