### ISSUE TITLE
X-powered-by not hidden

### ISSUE THREAD

**Issue by jfrelik** [Baroshem/nuxt-security#93]
### Version

nuxt-security: 0.10.1
nuxt: 3.1.0

### Steps to reproduce
`pnpx nuxi@latest init`
`pnpm add nuxt-security`
add nuxt-security to nuxt config

### What is Expected?
x-powered-by header to be hidden
### What is actually happening?
![image](https://user-images.githubusercontent.com/21983038/215346699-50113205-d5e9-4814-86a3-c4a077a12a53.png)

**Comment by Baroshem** [comment]
Hey, 

are you using it in development or production environment?

**Comment by Baroshem** [comment]
I see. I think there was a change in how nitro is handling extensions in the 3.1.0 version.

I will do some research and let you know.

**Comment by Baroshem** [comment]
I see where the problem is. 

In the recent version of nuxt, the powered by header name was replaced from `X-Powered-By` to `'x-powered-by'`. I will create a fix that I will release in the upcoming days.
